---
- name: Install pass
  pacman: name=pass state=present

- name: Install pass-otp
  pacman: name=pass-otp state=present

- name: Install pass-update
  aur: name=pass-update

- name: Install rofi-pass
  aur: name=rofi-pass
