---
- name: Report ansible_product_version
  debug:
    msg: |
      ansible_product_version: {{ ansible_product_version }}
      ansible_product_name: {{ ansible_product_name }}
      ansible_system_vendor: {{ ansible_system_vendor }}
  tags: base

# On first run, path won't exist yet, but maybe we can still create link here
- name: Setup provision command
  file:
    src: "/home/{{ user.name }}/{{ dotfiles.path }}/provision"
    dest: /usr/local/bin/provision
    state: link
    force: yes
  when: dotfiles.path is defined

- import_tasks: user.yml
- import_tasks: package_manager_setup.yml
- import_tasks: sudo.yml
- import_tasks: packages.yml
- import_tasks: shell.yml
- import_tasks: journal.yml

# # Added this when troubleshooting irregular temp readings in i3 setup
# # https://wiki.archlinux.org/index.php/lm_sensors
# - name: Run sensors-detect
#   command: sensors-detect --auto
#   become: yes
#   changed_when: False

# - name: Enable full Polkit logging
#   copy:
#     src: 00-log-access.rules
#     dest: /etc/polkit-1/rules.d/00-log-access.rules
#   become: yes

# - name: Enable Polkit without password
#   copy:
#     src: 49-nopasswd_global.rules
#     dest: /etc/polkit-1/rules.d/49-nopasswd_global.rules
#   become: yes
