---
- name: Report ansible_product_version
  debug:
    msg: "ansible_product_version: {{ ansible_product_version }}"

- name: Copy pacman configuration file
  copy:
    src: pacman.conf
    dest: /etc/pacman.conf

- name: Refresh pacman mirrors
  pacman:
    update_cache: yes

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined

- import_tasks: user.yml
- import_tasks: sudo.yml
- import_tasks: packages.yml
- import_tasks: shell.yml
- import_tasks: journal.yml

- name: Setup provision command
  file:
    src: "/home/{{ user.name }}/{{ dotfiles.source }}/provision"
    dest: /usr/local/bin/provision
    state: link

# Added this when troubleshooting irregular temp readings in i3 setup
# https://wiki.archlinux.org/index.php/lm_sensors
- name: Run sensors-detect
  command: sensors-detect --auto
  become: yes
