---
- name: Install Sublime Text GPG key
  shell: |
    curl -O https://download.sublimetext.com/sublimehq-pub.gpg
    pacman-key --add sublimehq-pub.gpg
    pacman-key --lsign-key 8A8F901A
    rm sublimehq-pub.gpg
  become: yes
- name: Report ansible_product_version
  debug:
    msg: |
      ansible_product_version: {{ ansible_product_version }}
      ansible_product_name: {{ ansible_product_name }}
      ansible_system_vendor: {{ ansible_system_vendor }}
  tags: base

- name: Copy pacman configuration file
  copy:
    src: pacman.conf
    dest: /etc/pacman.conf

- name: Refresh pacman mirrors
  pacman:
    update_cache: yes

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined

- import_tasks: user.yml
- import_tasks: sudo.yml
- import_tasks: packages.yml
- import_tasks: shell.yml
- import_tasks: journal.yml

#- name: Setup provision command
#  file:
#    src: "/home/{{ user.name }}/{{ dotfiles.source }}/provision"
#    dest: /usr/local/bin/provision
#    state: link

# Added this when troubleshooting irregular temp readings in i3 setup
# https://wiki.archlinux.org/index.php/lm_sensors
- name: Run sensors-detect
  command: sensors-detect --auto
  become: yes

- name: Enable full Polkit logging
  copy:
    src: 00-log-access.rules
    dest: /etc/polkit-1/rules.d/00-log-access.rules
  become: yes

- name: Enable Polkit without password
  copy:
    src: 49-nopasswd_global.rules
    dest: /etc/polkit-1/rules.d/49-nopasswd_global.rules
  become: yes
