---
- name: Report ansible_product_version
  debug:
    msg: |
      ansible_product_version: {{ ansible_product_version }}
      ansible_product_name: {{ ansible_product_name }}
      ansible_system_vendor: {{ ansible_system_vendor }}
  tags: base

- import_tasks: packages.yml
- import_tasks: shell.yml

