---

# This needs to be done before using pacman
# TODO: really? or just before installing packages?

- name: Check if Sublime GPG key already added
  when: "'sublime-text' in packages.editors"
  shell: pacman-key --list-keys | grep -q 8A8F901A
  register: sublime_key_check
  ignore_errors: True
  changed_when: False
- name: Install Sublime Text GPG key
  when: "'sublime-text' in packages.editors and sublime_key_check is failed"
  become: yes
  block:
    - name: Download key
      get_url:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        dest: /tmp
        mode: 755
    - name: Add key
      command: pacman-key --add sublimehq-pub.gpg
      args:
        chdir: /tmp
    - name: Sign key
      command: pacman-key --lsign-key 8A8F901A
    - name: Delete keyfile
      file:
        path: /tmp/sublimehq-pub.gpg
        state: absent

