---
- name: Upgrade all packages
  aur:
    upgrade: yes
    skip_installed: no
  become: yes
  become_user: aur_builder

- name: Install universal base packages
  pacman:
    name: "{{ query('flattened', '{{ packages.base }}') }}"
    state: present

- name: Install AUR base packages
  aur:
    name: "{{ packages.base_aur }}"
  become: yes
  become_user: aur_builder

- name: Install firmware update utility
  pacman:
    name: fwupd
    state: present
- name: Refresh firmware update metadata from remote server
  command: fwupdmgr refresh
  changed_when: False
- name: Check if firmware updates available
  command: fwupdmgr get-updates
  register: result
  changed_when: False
- name: Update firmware
  when: "'No upgrades' not in result.stderr or 'No updatable' in result.stderr"
  command: fwupdmgr update --force
  become: yes
