---
- name: Install universal base packages
  pacman:
    name: "{{ query('flattened', '{{ packages.base }}') }}"
    state: present

- name: Create pacman hook directory
  file:
    path: "/etc/pacman.d/hooks"
    state: directory

- name: Push pacman mirror list update hook
  copy:
    src: "mirrorlist.hook"
    dest: "/etc/pacman.d/hooks/mirrorlist.hook"

- name: Install AUR helper
  aur:
    name: aurman
    use: auto
    skip_pgp_check: yes
  become: yes
  become_user: aur_builder

# This is redundant with dotfiles but here for ordering
- name: Configure Aurman
  blockinfile:
    dest: "/home/{{ user.name }}/.config/aurman/aurman_config"
    state: present
    block: |
      [miscellaneous]
      no_sudo_loop
    create: yes
    mode: "u=rw,g=r,o=r"

- name: Upgrade all packages
  aur:
    upgrade: yes
    skip_installed: no
  become: yes
  become_user: aur_builder

- name: Install AUR base packages
  aur:
    name: "{{ packages.base_aur }}"
  become: yes
  become_user: aur_builder

- name: Push pacman cache cleanup service
  copy:
    src: "paccache.service"
    dest: "/etc/systemd/system/paccache.service"
  notify:
    - reload systemd config

- name: Push pacman cache cleanup timer
  copy:
    src: "paccache.timer"
    dest: "/etc/systemd/system/paccache.timer"
  notify:
    - reload systemd config
    - restart paccache

- name: Enable and start pacman cache cleanup timer
  service:
    name: "paccache.timer"
    enabled: yes
    state: started
