---
- name: Copy pacman configuration file
  copy:
    src: pacman.conf
    dest: /etc/pacman.conf

- name: Push pacman cache cleanup service
  copy:
    src: "paccache.service"
    dest: "/etc/systemd/system/paccache.service"
  notify:
    - reload systemd config

- name: Push pacman cache cleanup timer
  copy:
    src: "paccache.timer"
    dest: "/etc/systemd/system/paccache.timer"
  notify:
    - reload systemd config
    - restart paccache

- name: Enable and start pacman cache cleanup timer
  service:
    name: "paccache.timer"
    enabled: yes
    state: started

- name: "Push pacman mirrors 'reflector' update script"
  copy:
    src: reflector-update.sh
    dest: /usr/local/bin/reflector-update
    mode: 0755

- name: Create pacman hook directory
  file:
    path: "/etc/pacman.d/hooks"
    state: directory

- name: Push pacman mirror list update hook
  copy:
    src: "mirrorlist.hook"
    dest: "/etc/pacman.d/hooks/mirrorlist.hook"

- name: Refresh pacman mirrors
  pacman:
    update_cache: yes
  changed_when: False

- name: Create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    # Picking ID < 1000 to auto hide on login screen
    uid: 998
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0644
    validate: 'visudo -cf %s'

- name: Install yay using makepkg if it isn't installed already
  aur:
    name: yay
    use: makepkg
    # state: present Usupported for aur module, weird
  become: yes
  become_user: aur_builder
