---
- name: Remove deprecated packages
  apt:
    name: "{{ packages.deprecated }}"
    state: absent
  become: yes

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes
  become: yes

- name: Install universal base packages
  apt:
    name: "{{ query('flattened', '{{ packages.base }}') }}"
    state: present

