---
- name: Remove deprecated packages
  pacman:
    name: "{{ packages.deprecated }}"
    state: absent
  become: yes

- name: Upgrade all packages
  aur:
    upgrade: yes
    skip_installed: no
  become: yes
  become_user: aur_builder

- name: Install universal base packages
  pacman:
    name: "{{ query('flattened', '{{ packages.base }}') }}"
    state: present

- name: Install AUR base packages
  aur:
    name: "{{ packages.base_aur }}"
  become: yes
  become_user: aur_builder

- name: Install firmware update utility
  pacman:
    name: fwupd
    state: present
- name: Refresh firmware update metadata from remote server
  # --force because returns error (2) if recently refreshed:
  # Firmware metadata last refresh: 3 minutes ago. Use --force to refresh again.
  command: fwupdmgr refresh --force
  changed_when: False
  
  #- name: Check if firmware updates available
  #command: fwupdmgr get-updates
  #register: result
  #changed_when: False
  #- name: Update firmware
  #when: "'No updates' not in result.stderr and 'No updatable' not in result.stderr"
  #command: fwupdmgr update --force
  #become: yes
