---
- become: yes
  block:
  - name: Install Zsh packages
    apt:
      name:
      - zsh-syntax-highlighting
      # doesn't exist - ttf-meslo-nerd-font-powerlevel10k
  - name: Clone oh-my-zsh repo
    git:
      repo: "git://github.com/robbyrussell/oh-my-zsh.git"
      dest: "/usr/local/google/home/{{ user.name }}/.oh-my-zsh"
      depth: 1
      update: yes
      accept_hostkey: yes
  - name: Clone history-search-multi-word repo
    git:
      repo: "git://github.com/zdharma/history-search-multi-word.git"
      dest: "/usr/local/google/home/{{ user.name }}/.oh-my-zsh/custom/plugins/history-search-multi-word"
      depth: 1
      update: yes
      accept_hostkey: yes
  - name: Clone powerlevel10k repo
    git:
      repo: "git://github.com/romkatv/powerlevel10k.git"
      dest: "/usr/local/google/home/{{ user.name }}/.oh-my-zsh/custom/themes/powerlevel10k"
      depth: 1
      update: yes
      accept_hostkey: yes
  - name: Install Tmux Plugin Manager
    git:
      repo: "git://github.com/tmux-plugins/tpm.git"
      dest: "/usr/local/google/home/{{ user.name }}/.tmux/plugins/tpm"
      depth: 1
      update: yes
      accept_hostkey: yes
  # # Tmux plugins get installed from Tmux, so not sure when this would get
  # # overwritten
  # - name: Patch tmux-logging delay
  #   lineinfile:
  #     path: "/usr/local/google/home/{{ user.name }}/.tmux/plugins/tmux-logging/scripts/check_tmux_version.sh"
  #     regexp: 'local display_duration="5000"'
  #     state: present
  #     line: '             local display_duration="500"'

