---
- name: Create user group
  group:
    name: "{{ user.group }}"
    state: present

- name: Create user and assign to group
  user:
    name: "{{ user.name }}"
    group: "{{ user.group }}"
    password: "{{ user.password|password_hash('sha512') }}"
    shell: "{{ user.shell }}"
    update_password: on_create
    uid: "{{ user.uid }}"
    append: yes

- name: Create user log dir
  file:
    path: "/home/{{ user.name }}/{{ user.log.dir }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  when: user.log.dir is defined

- name: Push logrotate config for user logs
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/user
  when: user.log.dir is defined

- name: Create AUR user
  user:
    name: aur_builder
    group: wheel
    password: "$1$salty$mESw5HXxgLa8HHTdZrG/7/"
    update_password: on_create

#TODO: still need to figure out what approach to use here
- name: Put AUR user in sudoers
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    # line: 'aur_builder ALL=(ALL) NOPASSWD: ALL'
    # was having inexplicable sudo password request
    # [sudo] password for aur_builder:
    create: yes
    validate: 'visudo -cf %s'
