---
- name: Install editors
  aur:
    name: "{{ item }}"
  become: yes
  become_user: aur_builder
  with_items: "{{ packages.editors }}"


- name: Make directory for Pathogen
  file:
    name: /home/{{ user.name }}/.vim/bundle
    state: directory
  become: yes
  become_user: "{{ user.name }}"

- name: Install Pathogen and Vim plugins
  git:
    repo: "git://github.com/{{ item.user }}/{{ item.repo }}.git"
    dest: "/home/{{ user.name }}/.vim/bundle/{{ item.repo }}"
    update: yes
    accept_hostkey: yes
    version: "{{ item.version | default('HEAD') }}"
  become: yes
  become_user: "{{ user.name }}"
  with_items:
    - { user: 'tpope', repo: 'vim-pathogen' }
    # remaps . in a way that plugins can tap into it:
    - { user: 'tpope', repo: 'vim-repeat' }
    - { user: 'tpope', repo: 'vim-surround' }
    - { user: 'tpope', repo: 'vim-speeddating' }
    - { user: 'christoomey', repo: 'vim-tmux-navigator' }
    # this looks interesting, but I am doing too much new stuff already
    # - { user: 'tpope', repo: 'vim-abolish' }
    - { user: 'tpope', repo: 'vim-commentary' }
    # seems redundant with vim-commentary:
    # - { user: 'scrooloose', repo: 'nerdcommenter' }
    - { user: 'Xuyuanp', repo: 'nerdtree-git-plugin' }
    - { user: 'scrooloose', repo: 'nerdtree' }
    # - { user: 'vim-scripts', repo: 'taglist.vim' }
    - { user: 'michaeljsmith', repo: 'vim-indent-object' }
    - { user: 'bronson', repo: 'vim-visual-star-search' }
    - { user: 'lifepillar', repo: 'vim-solarized8' }
    - { user: 'tomasr', repo: 'molokai' }
    # SnipMate
    # - { user: 'tomtom', repo: 'tlib_vim' }
    # - { user: 'MarcWeber', repo: 'vim-addon-mw-utils' }
    # - { user: 'garbas', repo: 'vim-snipmate' }
    # SnipMate optional, Ultisnips optional
    # - { user: 'honza', repo: 'vim-snippets' }
    # Vim Airline
    - { user: 'vim-airline', repo: 'vim-airline' }
    - { user: 'vim-airline', repo: 'vim-airline-themes' }
    - { user: 'psf', repo: 'black' }
    # full path fuzzy file, buffer, mru, tag, ... finder
    # TODO: consider https://github.com/Shougo/denite.nvim
    # - { user: 'ctrlpvim', repo: 'ctrlp.vim' }
    - { user: 'junegunn', repo: 'fzf.vim' }
    # better indent code folding (for Python)
    - { user: 'tmhedberg', repo: 'SimpylFold' }
    # recommended for SimplyFold, not required
    - { user: 'Konfekt', repo: 'FastFold' }
    # using autocomplete plugin "YouCompleteMe" via AUR package
    # vim-youcompleteme-git
    # - { user: 'Valloric', repo: 'YouCompleteMe' }
    # - { user: 'ervandew', repo: 'supertab' }
    # Git integration: :G, :Gwrite, :Gmove, etc.
    - { user: 'tpope', repo: 'vim-fugitive' }
    - { user: 'tommcdo', repo: 'vim-fubitive' }  # Bitbucket support
    # Tag sidebar
    - { user: 'majutsushi', repo: 'tagbar' }
    # Ultisnips, used by YouCompleteMe
    # - { user: 'SirVer', repo: 'ultisnips' }
    # Trying another thing to maybe get signatures... which needs Jedi...
    # - { user: 'ColinKennedy', repo: 'vim-python-function-expander' }
    # - { user: 'davidhalter', repo: 'jedi-vim' }
    # - { user: '', repo: '' }
    #
    # TODO: check out https://github.com/terryma/vim-multiple-cursors
    # TODO: check out https://github.com/w0rp/ale
    #   ~/.vim/ftplugin/python.vim:
    #   let b:ale_linters = ['pyflakes', 'flake8', 'pylint']
    #   let b:ale_fixers = ['eslint']
    #   let b:ale_fix_on_save = 1

    # Vimwiki
    - { user: 'vimwiki', repo: 'vimwiki', version: 'dev' }
    #   TaskWarrior integration
    #     Requires python-tasklib from AUR
    - { user: 'tbabej', repo: 'taskwiki' }
    #     Enables gridview:
    - { user: 'farseer90718', repo: 'vim-taskwarrior' }
    #     Adds color support in charts:
    - { user: 'powerman', repo: 'vim-plugin-AnsiEsc' }

    # Jinja template syntax (using for Pelican static site generator)
    - { user: 'lepture', repo: 'vim-jinja' }

- name: Install python-tasklib for TaskWarrior-Vimwiki integration
  aur:
    name: "{{ item }}"
  become: yes
  become_user: aur_builder
  with_items:
    - python-tasklib
