---
- name: Install Sublime Text GPG key
  shell: |
    curl -O https://download.sublimetext.com/sublimehq-pub.gpg
    pacman-key --add sublimehq-pub.gpg
    pacman-key --lsign-key 8A8F901A
    rm sublimehq-pub.gpg
  become: yes

- name: Install editors
  aur:
    name: "{{ item }}"
  become: yes
  become_user: aur_builder
  with_items: "{{ packages.editors }}"


- name: Make directory for Pathogen
  file:
    name: /home/{{ user.name }}/.vim/bundle
    state: directory
  become: yes
  become_user: "{{ user.name }}"

- name: Install Pathogen and Vim plugins
  git:
    repo: "git://github.com/{{ item.user }}/{{ item.repo }}.git"
    dest: "/home/{{ user.name }}/.vim/bundle/{{ item.repo }}"
    update: yes
    accept_hostkey: yes
  become: yes
  become_user: "{{ user.name }}"
  with_items:
    - { user: 'tpope', repo: 'vim-pathogen' }
    - { user: 'tpope', repo: 'vim-repeat' }
    - { user: 'tpope', repo: 'vim-surround' }
    - { user: 'tpope', repo: 'vim-speeddating' }
    - { user: 'christoomey', repo: 'vim-tmux-navigator' }
    # this looks interesting, but I am doing too much new stuff already
    # - { user: 'tpope', repo: 'vim-abolish' }
    - { user: 'tpope', repo: 'vim-commentary' }
    - { user: 'scrooloose', repo: 'nerdcommenter' }
    - { user: 'Xuyuanp', repo: 'nerdtree-git-plugin' }
    - { user: 'scrooloose', repo: 'nerdtree' }
    - { user: 'vim-scripts', repo: 'taglist.vim' }
    - { user: 'michaeljsmith', repo: 'vim-indent-object' }
    - { user: 'bronson', repo: 'vim-visual-star-search' }
    - { user: 'lifepillar', repo: 'vim-solarized8' }
    - { user: 'tomasr', repo: 'molokai' }
    - { user: 'lifepillar', repo: 'vim-solarized8' }
    # SnipMate
    - { user: 'tomtom', repo: 'tlib_vim' }
    - { user: 'MarcWeber', repo: 'vim-addon-mw-utils' }
    - { user: 'garbas', repo: 'vim-snipmate' }
    # SnipMate optional
    - { user: 'honza', repo: 'vim-snippets' }
    # Vim Airline
    - { user: 'vim-airline', repo: 'vim-airline' }
    - { user: 'vim-airline', repo: 'vim-airline-themes' }
    - { user: 'ambv', repo: 'black' }
    # full path fuzzy file, buffer, mru, tag, ... finder
    - { user: 'ctrlpvim', repo: 'ctrlp.vim' }
    # better indent code folding (for Python)
    - { user: 'tmhedberg', repo: 'SimpylFold' }
    # recommended for SimplyFold, not required
    - { user: 'Konfekt', repo: 'FastFold' }

