---
- name: Install hunspell
  pacman:
    name:
      - hunspell
      - hunspell-en_US
    state: present

- name: Install aspell
  pacman:
    name:
      - aspell
      - aspell-en
    state: present
