---
- name: Install Xorg packages
  aur:
    name: "{{ item }}"
  become: yes
  become_user: aur_builder
  with_items:
    - xorg-server
    - xorg-xinit
    - xorg-xmodmap
    - xorg-xdpyinfo
    - xorg-xev
    - xorg-sessreg
    - xautomation
    - xdg-user-dirs
    - sxhkd
    - unclutter
    - autorandr-git
    - srandrd
    - autocutsel
    - xvkbd # virtual keyboard, need binary for my xbindkeysrc paste command 

- name: Create user directories
  command: /usr/bin/xdg-user-dirs-update
  become: yes
  become_user: "{{ user.name }}"

# following should be replaced with `xdg-user-dirs-update --set DESKTOP ~`
- name: Change desktop folder
  become: yes
  become_user: "{{ user.name }}"
  lineinfile:
    path: /home/{{ user.name }}/.config/user-dirs.dirs
    regexp: "^XDG_DESKTOP_DIR="
    state: present
    line: 'XDG_DESKTOP_DIR="$HOME/"'

- name: Enable middle click scrolling
  copy:
    src: 30-scroll.conf
    dest: /etc/X11/xorg.conf.d/30-scroll.conf
  when: middle_click_scroll is defined and middle_click_scroll == True

- name: Enable gestures
  aur:
    name: "{{ item }}"
  become: yes
  become_user: aur_builder
  with_items:
    - libinput-gestures

- name: Enable natural scrolling
  copy:
    src: 31-scroll-direction.conf
    dest: /etc/X11/xorg.conf.d/31-scroll-direction.conf

- name: Check for NVIDIA graphics card
  command: lspci -k | grep -i nvidia
  register: nvidia_check
  failed_when: False
  changed_when: False

- name: Intel setup
  when: nvidia_check.rc == 1
  become: yes
  block:
  - name: "Intel graphics: kernel mode setting"
    become: yes
    lineinfile:
      path: /etc/mkinitcpio.conf
      regexp: "^MODULES=\\(((?:(?!{{item}}).)*)\\)"
      backrefs: yes
      state: present
      line: "MODULES=(\\1 {{item}})"
    with_items:
      - i915
  # Needed to delete this file to get displays to load, didn't investigate
  # https://wiki.archlinux.org/index.php/intel_graphics
  - name: "Intel graphics: take advantage of some driver options"
    copy:
      src: 20-intel.conf
      dest: /etc/X11/xorg.conf.d/20-intel.conf
  - name: "Intel graphics: Install packages"
    aur:
      name: "{{ item }}"
    become_user: aur_builder
    with_items:
      - libva-intel-driver

- name: NVIDIA setup
  when: nvidia_check.rc == 0
  become: yes
  block:
  - name: "NVIDIA: direct rendering manager: kernel mode setting: add kernel modules"
    lineinfile:
      path: /etc/mkinitcpio.conf
      regexp: "^MODULES=\\(((?:(?!{{item}}).)*)\\)"
      backrefs: yes
      state: present
      line: "MODULES=(\\1 {{item}})"
    with_items:
      - nvidia
      - nvidia_modeset
      - nvidia_uvm
      - nvidia_drm
  - name: "NVIDIA: direct rendering manager: add kernel parameter"
    lineinfile:
      path: /boot/loader/entries/arch.conf
      regexp: "^options ((?:(?!{{item}}).)*)"
      backrefs: yes
      state: present
      line: "options \\1 {{item}}"
    with_items:
      - nvidia-drm.modeset=1
  - name: "NVIDIA: Install Pacman hook"
    copy:
      src: nvidia.hook
      dest: /etc/pacman.d/hooks/nvidia.hook
      mode: 0644
  - name: "NVIDIA: Remove default Xorg config"
    file:
      path: /etc/X11/xorg.conf
      state: absent
  - name: "NVIDIA: Install Xorg config overrides"
    copy:
      src: 20-nvidia.conf
      dest: /etc/X11/xorg.conf.d/20-nvidia.conf
      mode: 0644
  - name: "NVIDIA: Install packages"
    aur:
      name: "{{ item }}"
    become_user: aur_builder
    with_items:
      - nvidia
      - cuda

- name: Add user to video group
  user:
    name: "{{ user.name }}"
    groups: video
    append: yes
