---
- name: Install Xorg packages
  apt:
    name:
      - autorandr
      # - autocutsel
      # - xvkbd # virtual keyboard, need binary for my xbindkeysrc paste command
  become: yes

# - name: Remove default ACPI events file
#   file:
#     path: /etc/acpi/events/anything
#     state: absent

- name: Enable middle click scrolling
  copy:
    src: 30-scroll.conf
    dest: /etc/X11/xorg.conf.d/30-scroll.conf

- name: Enable faster mouse
  copy:
    src: 50-mouse-acceleration.conf
    dest: /etc/X11/xorg.conf.d/50-mouse-acceleration.conf

- name: Enable natural scrolling
  copy:
    src: 31-scroll-direction.conf
    dest: /etc/X11/xorg.conf.d/31-scroll-direction.conf

- name: Kernel module to enable controlling external monitor
  copy:
    src: i2c-dev.conf
    dest: /etc/modules-load.d/i2c-dev.conf
- name: Udev rule to enable controlling external monitor
  copy:
    src: 45-ddcutil-i2c.rules
    dest: /etc/udev/rules.d/45-ddcutil-i2c.rules
- name: Install ddcutil to control external monitor
  apt:
    name: ddcutil
  become: yes
