---
- name: Install Xorg
  pacman: name=xorg-server state=present

- name: Install Xinit
  pacman: name=xorg-xinit state=present

- name: Install xmodmap
  pacman: name=xorg-xmodmap state=present

- name: Install xdpyinfo
  pacman: name=xorg-xdpyinfo state=present

- name: Install xev
  pacman: name=xorg-xev state=present

- name: Install xorg-sessreg
  pacman: name=xorg-sessreg state=present

- name: Install xautomation
  pacman: name=xautomation state=present

- name: Install video driver(s)
  pacman: name={{ item }} state=present
  with_items: "{{ video_drivers | default([]) }}"

- name: Add user to video group
  user: name={{ user.name }} groups=video append=yes

- name: Enable middle-click scrolling
  copy: src=30-scroll.conf dest=/etc/X11/xorg.conf.d/30-scroll.conf
  when: middle_click_scroll is defined and middle_click_scroll == True

- name: Enable natural scrolling
  copy: src=31-scroll-direction.conf dest=/etc/X11/xorg.conf.d/31-scroll-direction.conf

- name: Install more X stuff
  aur:
    name: "{{ item }}"
  become: yes
  become_user: aur_builder
  with_items:
    - sxhkd
    - unclutter
    - autorandr-git
    - srandrd
    - autocutsel

- import_tasks: xdg.yml
