---
- name: Install RedShift and dependencies
  pacman: name={{ item }} state=present
  with_items:
    - librsvg
    - python-gobject
    - python-xdg
    - redshift

- name: Allow RedShift to access geoclue
  blockinfile:
    dest: /etc/geoclue/geoclue.conf
    block: |
      [redshift]
      allowed=true
      system=false
      users=
