---
- name: Install Nginx
  aur:
    name: "{{ item }}"
  become: yes
  become_user: aur_builder
  with_items:
    - nginx
    - certbot-nginx

- name: Enable and start Nginx
  service:
    name: nginx
    enabled: yes
    state: started

- name: Create service to run the idle checker script
  copy:
    src: certbot.service
    dest: /etc/systemd/system/certbot.service
    mode: 0644

- name: Create timer to launch the certbot renew service
  copy:
    src: certbot.timer
    dest: /etc/systemd/system/certbot.timer
    mode: 0644
  notify:
    - reload systemd config

- name: Enable Certbox Timer
  service:
    name: certbot.timer
    enabled: yes
    state: started

- name: Install Transmission CLI
  pacman:
    name: transmission-cli
    state: present
  become: yes

#- name: Set Transmission user
#  templatecopy:
#    dest: /etc/systemd/system/transmission.service.d/username.conf
#[Service]
#User={{ user.name }}

# Enable unit, start unit

