#!/bin/bash

# this is executed by arch-chroot

set -o xtrace
set -o errexit

CRYPTDEVICE=${1:-}
HOSTNAME=${2:-}

echo "$HOSTNAME" > /etc/hostname
# Setup system clock
ln -f -s /usr/share/zoneinfo/US/Pacific /etc/localtime
hwclock --systohc --utc

# Generate locale
# https://wiki.archlinux.org/index.php/Locale#LC_TIME:_date_and_time_format
LANG=en_US.UTF-8
TIME=en_DK.UTF-8
{ echo $LANG UTF-8; echo $TIME UTF-8; } >> /etc/locale.gen
locale-gen
# I forgot the purpose of LC_ALL= here:
{ echo LANG=$LANG; echo LC_TIME=$TIME; echo LC_ALL=; } >> /etc/locale.conf

# Setup virtual console config (the Ctrl+Alt+F2, etc., one)
f=/etc/vconsole.conf
echo KEYMAP=dvorak >> $f
# Next two enable larger font on small HiDPI screen, requires terminus-font pkg
echo FONT=ter-p32n >> $f
echo FONT_MAP=8859-2 >> $f

echo -e "127.0.0.1\tlocalhost" >> /etc/hosts
echo -e "::1\tlocalhost" >> /etc/hosts
echo -e "127.0.1.1\t$(cat /etc/hostname)" >> /etc/hosts
systemctl enable NetworkManager

# Set password for root
passwd

# Configure mkinitcpio with modules needed for the initrd image
# https://git.archlinux.org/mkinitcpio.git/tree/mkinitcpio.conf
# the consolefont line is to allow larger font for HiDPS small screens
# the keyboard lines are to prevent autodetect from pruning drivers too much
# to be able to boot with a different keyboard than when initrd image built
sed -i -e 's/^MODULES=()/MODULES=(ext4)/' \
       -e '/^HOOKS.*block filesystems/s/filesystems/encrypt lvm2 resume filesystems/' \
       -e '/^HOOKS.*block encrypt/s/encrypt/keymap consolefont encrypt/' \
       -e '/^HOOKS.*udev autodetect/s/ keyboard//' \
       -e '/^HOOKS.*/s/autodetect/keyboard autodetect/' \
       /etc/mkinitcpio.conf

# Regenerate initrd image
mkinitcpio -p linux

# Setup systembootd (grub will not work on nvme at this moment)
bootctl --path=/boot install

# Create loader.conf
f=/boot/loader/loader.conf
echo 'default arch' >> $f
echo 'timeout 10' >> $f
echo 'editor 1' >> $f
# Enable larger text on tiny HiDPI screens (XPS 13)
echo 'console-mode 2' >> $f

# Create arch.conf
f=/boot/loader/entries/arch.conf
echo "title Arch Linux" >> $f
echo "linux /vmlinuz-linux" >> $f
echo "initrd /initramfs-linux.img" >> $f
# Could also deal with HiDPI small screen with video=1024x768
echo "options cryptdevice=UUID=$(blkid -o value -s UUID $CRYPTDEVICE):vg0 root=/dev/mapper/vg0-root resume=/dev/mapper/vg0-swap rw vsyscall=emulate quiet mem_sleep_default=deep" >> $f

# Exit new system and go into the cd shell
exit
