#!/bin/bash
set -o xtrace
set -o errexit

err_report () {
  echo "Error on line $1"
  rm -rf /mnt/installer
  rm arch.iso
}

clean_up () {
  umount -l /mnt/installer/* | true
  umount -f /mnt/installer/* | true
  umount ${DEV}1 | true
  umount ${DEV}2 | true
  rm -rf /mnt/installer
  rm arch.iso
}

main () {
  trap 'err_report $LINENO' ERR INT TERM

  YM=$(date "+%Y.%m")

  DEV=${1:-/dev/sda}
  URL=${2:-http://mirror.rackspace.com/archlinux/iso/$YM.01/archlinux-$YM.01-x86_64.iso}

  # download Arch installer
  [[ -f arch.iso ]] || wget -O arch.iso $URL

  # Protect against "Error: Partition(s) on /dev/sdg are being used."
  # which might happen if we canceled due to a super slow download, etc.
  dd if=/dev/zero of=$DEV bs=512 count=1024
  # partition device: 1GiB fat32, remaining space as ext4
  parted --script $DEV mklabel gpt mkpart primary fat32 1MiB 1GiB set 1 boot on mkpart primary ext4 1GiB 100%
  partprobe
  mkfs.fat ${DEV}1
  mkfs.ext4 -F ${DEV}2

  # copy installation files to fat32 partition, dotfiles to ext4 partition
  mkdir -p /mnt/installer/{install,extras}
  mount ${DEV}1 /mnt/installer/install
  bsdtar -x --exclude=syslinux/ -f arch.iso -C /mnt/installer/install
  mount ${DEV}2 /mnt/installer/extras
  git clone https://github.com/CNG/dotfiles.git /mnt/installer/extras/dotfiles
  sync

  # change to boot by UUID so we can boot without making label match month name
  find /mnt/installer/install/loader/entries -name "*.conf" | \
    xargs sed -E -i "s|archisolabel=\S+|archisodevice=/dev/disk/by-uuid/$(blkid -o value -s UUID ${DEV}1)|"

  trap - ERR
  clean_up
}

main "$@"

