---
- name: Install GreetD and ReGreet
  pacman:
    name:
      - greetd-regreet
    state: present
  become: yes

- name: Create background dir
  file:
    path: /usr/share/backgrounds
    state: directory

- name: Push greeter background
  copy:
    src: taipei.jpg
    dest: /usr/share/backgrounds/greeter.jpg
    mode: 0666

- name: Create Sway config file
  copy:
    src: sway-config
    dest: /etc/greetd/sway-config
    mode: 0644

- name: Create GreetD config file
  copy:
    src: greetd-config.toml
    dest: /etc/greetd/config.toml
    mode: 0644

- name: Create ReGreet config file
  copy:
    src: regreet-config.toml
    dest: /etc/greetd/regreet.toml
    mode: 0644

- name: Enable GreetD to start upon boot
  service:
    name: greetd
    enabled: yes
