---
- name: Install vagrant
  pacman: name=vagrant state=present

- name: Install consul
  pacman: name=consul state=present

- name: Install terraform
  pacman: name=terraform state=present

- name: Install vault and nomad
  aur: name={{ item }}
  with_items:
    - vault-bin
    - nomad
