---
- name: Install OpenVPN
  pacman: name=openvpn state=present

- name: Install MTR
  pacman: name=mtr state=present

- name: Install net-tools
  pacman: name=net-tools state=present

- name: Install bind-tools
  pacman: name=bind-tools state=present

- name: Install whois
  pacman: name=whois state=present

- name: Install netcat
  pacman: name=gnu-netcat state=present

- name: Install lftp
  pacman: name=lftp state=present

- name: Install nmap
  pacman: name=nmap state=present

- name: Install tcpdump
  pacman: name=tcpdump state=present

- name: Install sshuttle
  pacman: name=sshuttle state=present

- name: Install pdsh
  aur: name=pdsh user={{ user.name }}
  tags:
    - aur

- name: Install wireshark
  pacman: name=wireshark-qt state=present

- name: Add user to wireshark group
  user: name={{ user.name }} groups=wireshark append=yes

- name: Install socat
  pacman: name=socat state=present
