#!/bin/sh

B='#00000000'  # blank
C='#ffffff22'  # clear ish
D='#ff00ffcc'  # default
T='#ee00eeee'  # text
W='#880000bb'  # wrong
V='#bb00bbbb'  # verifying

tempbg=/tmp/lock.png
lockbg=$HOME/.config/windows.jpg
if [[ -e $lockbg ]]; then
  res=$(xdpyinfo | grep -oP 'dimensions: +[\dx]+' | grep -oP '[\dx]+')
  convert $lockbg -resize "${res}!" $tempbg
else
  # Take a screenshot:
  scrot $tempbg
  # Create a blur on the shot:
  convert $tempbg -paint 5 $tempbg
fi

i3lock \
--image=$tempbg       \
--insidevercolor=$C   \
--ringvercolor=$V     \
\
--insidewrongcolor=$C \
--ringwrongcolor=$W   \
\
--insidecolor=$B      \
--ringcolor=$D        \
--linecolor=$B        \
--separatorcolor=$D   \
\
--verifcolor=$T       \
--wrongcolor=$T       \
--timecolor=$T        \
--datecolor=$T        \
--layoutcolor=$T      \
--keyhlcolor=$W       \
--bshlcolor=$W        \
\
# --screen 1            \
--blur 25             \
--clock               \
# --indicator           \
--timestr="%H:%M:%S"  \
--datestr="%A, %m %Y" \
--keylayout 2         \
\
--radius=500 \
--ring-width=20 \
--ignore-empty-password \
--show-failed-attempts \

# --veriftext="Drinking verification can..."
# --wrongtext="Nope!"
# --textsize=20
# --modsize=10
# --timefont=comic-sans
# --datefont=monofur
# etc

