---
- name: restart pulse as user
  systemd: name=pulseaudio.service user=yes state=restarted
  become: yes
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
