---
- name: Install cronie
  pacman:
    name:
      - cronie
      - util-linux  # provides flock, for exclusivity locking
    state: present

- name: Enable cronie
  service:
    name: cronie.service
    enabled: yes
    state: started

# TODO https://wiki.archlinux.org/title/cron#Ensuring_exclusivity