---
- name: Install CUPS and drivers
  pacman: name={{ item }} state=present
  with_items:
    - ghostscript
    - gsfonts
    - cups
    - cups-pdf
    - gutenprint
    - hplip
  tags:
    - cups

- name: Add a print admin group
  group: name=printadmin state=present
  tags:
    - cups

- name: Allow the print admin group to administer CUPS
  lineinfile: dest=/etc/cups/cups-files.conf
              regexp=^SystemGroup
              state=present
              line="SystemGroup sys root printadmin"
  tags:
    - cups

- name: Add the user to the print and print admin groups
  user: name={{ user.name }} groups=printadmin,lp append=yes
  tags:
    - cups

- name: Enable and start CUPS
  service: name=org.cups.cupsd.service enabled=yes state=started
  tags:
    - cups
