---
- name: Install w3m
  pacman:
    name: w3m
    state: present

# TODO: see about setting 'ui.context_menus.after_mouseup' true automatically
# lineinfile: line: user_pref("ui.context_menus.after_mouseup", true);
# file like /home/cgorichanaz/.mozilla/firefox/rwv4hwau.default/prefs.js
# less /home/cgorichanaz/.mozilla/firefox/profiles.ini
- name: Install Firefox
  pacman:
    name: firefox
    state: present

- name: Install Chromium
  pacman:
    name: chromium
    state: present

- name: Install tor-browser
  aur:
    name: tor-browser
    skip_pgp_check: yes
  become: yes
  become_user: aur_builder

- name: Verify mimeapps.list exists
  file:
    path: /etc/xdg/mimeapps.list
    state: touch

- name: Setup browsers firejail
  when: "'firejail' in roles"
  block:

  - name: Jail Firefox
    file:
      src: /usr/bin/firejail
      dest: /usr/local/bin/firefox
      state: link
  - name: Verify Firefox firejail local profile exists
    file:
      path: /etc/firejail/firefox.local
      state: file
  - name: Restrict Firefox access to /etc
    lineinfile:
      dest: /etc/firejail/firefox.local
      regexp: "^private-etc"
      line: "private-etc firejail,passwd,group,hostname,hosts,nsswitch.conf,resolv.conf,gtk-2.0,gtk-3.0,fonts,mime.types,asound.conf,pulse,localtime"

  - name: Jail Chromium
    file:
      src: /usr/bin/firejail
      dest: /usr/local/bin/chromium
      state: link
  - name: Verify Chromium firejail local profile exists
    file:
      path: /etc/firejail/chromium.local
      state: file
  - name: Restrict Chromium access to /etc
    lineinfile:
      dest: /etc/firejail/chromium.local
      regexp: "^private-etc"
      line: "private-etc firejail,passwd,group,hostname,hosts,nsswitch.conf,resolv.conf,gtk-2.0,gtk-3.0,fonts,mime.types,asound.conf,pulse,localtime"

  - name: Jail tor-browser
    file:
      src: /usr/bin/firejail
      dest: /usr/local/bin/tor-browser
      state: link

- name: Remove browsers firejail
  when: "'firejail' not in roles"
  block:

  - name: Unjail Firefox
    file:
      path: /usr/local/bin/firefox
      state: absent
  - name: Remove Firefox firejail local profile
    file:
      path: /etc/firejail/firefox.local
      state: absent

  - name: Unjail Chromium
    file:
      path: /usr/local/bin/chromium
      state: absent
  - name: Remove Chromium firejail local profile
    file:
      path: /etc/firejail/chromium.local
      state: absent

  - name: Unjail tor-browser
    file:
      dest: /usr/local/bin/tor-browser
      state: absent


# - name: Install Pepper Flash
#   pacman: name=pepper-flash state=present
# - name: Push rofi browser chooser
#   template: src=browser.sh.j2 dest=/usr/local/bin/browser mode=0755
# - name: Create local desktop application dir
#   file: path=/usr/local/share/applications state=directory
# - name: Push rofi browser chooser desktop file
#   copy: src=browser.desktop dest=/usr/local/share/applications/browser.desktop
# - name: Set rofi browser chooser as default application for relevant mimetypes
#   lineinfile:
#     dest: /etc/xdg/mimeapps.list
#     regexp: "{{ item.regexp }}"
#     line: "{{ item.line }}"
#   with_items:
#     - { regexp: '^text/html=', line: 'text/html=browser.desktop' }
#     - { regexp: '^text/xml=', line: 'text/xml=browser.desktop' }
#     - { regexp: '^text/mml=', line: 'text/mml=browser.desktop' }
#     - { regexp: '^application/xhtml\+xml=', line: 'application/xhtml+xml=browser.desktop' }
#     - { regexp: '^application/xml=', line: 'application/xml=browser.desktop' }
#     - { regexp: '^x-scheme-handler/http=', line: 'x-scheme-handler/http=browser.desktop' }
#     - { regexp: '^x-scheme-handler/https=', line: 'x-scheme-handler/https=browser.desktop' }

# - name: Install surfraw
#   pacman: name=surfraw state=present
# - name: Configure surfraw browser
#   lineinfile:
#     dest: /etc/xdg/surfraw/conf
#     regexp: '^def   SURFRAW_graphical_browser	'
#     line: 'def   SURFRAW_graphical_browser	/usr/local/bin/browser'
# - name: Push surfraw-rofi script
#   copy: src=surfraw-rofi dest=/usr/local/bin/surfraw-rofi mode=0755
