---
- name: Remove rtorrent
  when: "'rtorrent' in roles"
  block:
  - name: Install rtorrent
    pacman:
      name: rtorrent
      state: present
  - name: Jail rtorrent
    when: "'firejail' in roles"
    file:
      src: /usr/bin/firejail
      dest: /usr/local/bin/rtorrent
      state: link

- name: Remove rtorrent
  when: "'rtorrent' not in roles"
  block:
  - name: Remove rtorrent
    pacman:
      name: rtorrent
      state: absent

- name: Unjail rtorrent
  when: "'firejail' not in roles"
  file:
    dest: /usr/local/bin/rtorrent
    state: absent
