---
- name: Install Sway tiling window manager
  aur:
    name: "{{ packages.sway }}"
  become: yes
  become_user: aur_builder

- name: Verify header in default applications file
  lineinfile:
    dest: /etc/xdg/mimeapps.list
    state: present
    line: '[Default Applications]'
    insertbefore: BOF
    create: yes
