user:
  name: votecharlie
  layout: dvorak

dotfiles:
  git_url: "git://github.com/CNG/dotfiles.git"
  path: dotfiles
  files_to_copy_not_link: "htoprc Preferences.sublime-settings copyq.conf"

# udisks:
#   auto_mount: True
#   shared_mount: True

desktop_environment: i3

packages:
  deprecated:
    - fritzing

  base:
    - [ git, git-lfs ]
    # - glances
    # - go
    - imwheel
    - zplug
    # - acpid
    - redshift  # blue light reduction
    - rcm
    - taskwarrior
    - spotify-client
    - silversearcher-ag  # better grep
    - grc  # Colorize logfiles and command output
    - highlight
    - htop
    # - iftop
    # - iotop
    # - iputils
    - jq
    # - ntop
    # - sysstat
    # - vnstat
    - fzf  # fuzzy finder
    - copyq  # clipboard manager
    # - enscript
    # - pandoc
    - taskwarrior
    - keychain  # keychain manager for openssh
    - google-cloud-sdk
    - google-sublime-text

  media:
    # - [ libraw, libpng, librsvg, openjpeg2, imagemagick ]
    - vlc
    # - zopfli  # compression
    # - vdhcoapp-bin  # Video Downloadhelper companion app
    # - guvcview  # webcam record
    # - gwenview  # best image viewer for KDE
    # - flac2all
    # - iscan-plugin-gt-x820  # Epson V600 scanner
    # - libheif
    # - gthumb
    # - handbrake
    # - mediainfo-gui
    # - youtube-dl
    # # misc media codecs and helpers
    # - exiv2
    # - flac
    # - gst-libav
    # - lame
    # - perl-image-exiftool
    # - x264
    # - [ kdenlive, recordmydesktop ]

  i3:
    - dex  # load autostarts
    - i3
    - i3blocks
    - xautolock
    - feh  # Set background
    - xinput
    # - scrot
    - rofi  # menu
    - xclip  # Used for Rofi cheatsheet/notes
    - playerctl  # media player controls
    # - qt5ct  # https://wiki.archlinux.org/index.php/Qt#Configuration_of_Qt5_apps_under_environments_other_than_KDE_Plasma
    - xbindkeys
    - xdotool  # for emulating 60% keyboard in i3 config
    # - xbacklight

