user:
  name: cgorichanaz
  fullname: Charlie Gorichanaz
  group: cgorichanaz
  email:  charlie@gorichanaz.com
  uid: 1000
  gid: 1000
  shell: /usr/bin/zsh
  layout: dvorak
  # # be sure to change the password after first run
  # password: test
  log:
    dir: log
    rotate: 8
dotfiles:
  git_url: "git://github.com/CNG/dotfiles.git"
  path: dotfiles
  files_to_copy_not_link: "htoprc Preferences.sublime-settings"
ssh_keys:
  - cng1408
  - cng1408s
  - id_rsa

# hostsctl:
#   url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

journal:
  max_size: 5G
ssh:
  port: 22
  # user_key: /root/id_rsa
  enable_sshd: True
udisks:
  auto_mount: True
  shared_mount: True

desktop_environment: sway
flags:
  - dummyflag
  - digikam
  # - server




# TODO

# samba_log: /var/log/samba.log
# samba_log_size: 60000
# gnupg:
#   enable_agent: True
#   emulate_ssh: True
# network:
#   spoof_mac: False
#   conn_check:
#     interval: 0
# fingerprint: False
# localtime:
#   run_on: all
# nameservers:
# - 1.1.1.1
# middle_click_scroll: True
# multitouch: True



packages:
  deprecated:
  base:
    - base-devel
    - man-db
    - man-pages
    - reflector  # For pacman mirror ranking
    - tmux
    - git
    - rsync
    - coreutils
    - dateutils
    - moreutils
    - bc
    - ruby
    - go
    # - kfind
    - lsof
    - strace
    - sysstat
    - inotify-tools  # For inotifywait
    - the_silver_searcher
    # - command-not-found  # may need to check if /etc/zsh/zprofile is sourced as it says it should be
    - grc  # Colorize logfiles and command output
    - highlight
    - htop
    - iftop
    - iotop
    - iputils
    - usbutils  # provides lsusb
    - jq
    - yq
    # - linux-headers
    - nfs-utils
    # - ntop
    # - pygmentize  # Python syntax highlighter
    # - qt5-webengine
    # - rsnapshot
    # - screen
    # - solaar
    - sqlitebrowser
    - tree
    # - vagrant
    # - vnstat
    - wget
    # - wireless_tools
    - firefox
    - neofetch
    - upower


  base_aur:
    - alacritty
    - google-chrome
    - upd72020x-fw  # resolve missing firmware warning xhci_pci
    # - ctmg
    # - imwheel
    # - miller
    # - myrepos
    # - python-systemd  # Ansible log to journal
    # - tmux-bash-completion
    # - zplug
    # - acpid
    # # Next two were on laptop only, adding here for consistency till I test why
    # - acpitool
    # - acpi_call-dkms
    # - redshift  # blue light reduction

  editors:
    - nano
    - sublime-text
    - vi
    - vim
    - obsidian
    # - gvim  # gvim (then don't need vim) required for clipboard/libX11 support
    # - fzf  # fuzzy finder
    # - python-black  # vim-codefmt uses system "black"

  filesystem:
    - dosfstools
    - ntfs-3g
    # - exfat-utils
    # - exfatprogs
    # - hfsprogs
    # no longer avail, check if still needed for mac migration
    # - hfsutils
    # - libguestfs  # mount VMDKs, large install
    # - gparted
    # - udftools

  fonts:
    - ttf-nerd-fonts-input
    - ttf-opensans
    - adobe-base-14-fonts
    - adobe-source-code-pro-fonts
    - ttf-adobe-source-fonts
    - ttf-fira-code
    - ttf-fira-mono
    - ttf-fira-sans
    - ttf-font-awesome-4
    - ttf-tahoma
    - ttf-ubuntu-font-family
    # Chinese
    - adobe-source-han-sans-cn-fonts
    - adobe-source-han-serif-cn-fonts
    - noto-fonts-cjk
    - wqy-microhei
    - wqy-microhei-lite
    - wqy-bitmapfont
    - wqy-zenhei
    - ttf-arphic-ukai
    - ttf-arphic-uming
  _TODO_fonts:
    - cantarell-fonts
    - gsfonts
    - noto-fonts
    - terminus-font
    - tex-gyre-fonts
    - ttc-iosevka
    - ttc-iosevka-aile
    - ttc-iosevka-ss08
    - ttf-bitstream-charter
    - ttf-bookerly
    - ttf-caladea
    - ttf-carlito
    - ttf-contemporary
    - ttf-cooper-hewitt
    - ttf-courier-prime
    - ttf-dejavu
    - ttf-droid
    - ttf-fantasque-sans-mono
    - ttf-heuristica
    - ttf-ibm-plex
    - ttf-inconsolata
    - ttf-iosevka
    - ttf-latex-xft-fonts
    - ttf-liberation
    - ttf-mac-fonts
    - ttf-merriweather
    - ttf-merriweather-sans
    - ttf-mplus-git
    - ttf-nanum
    - ttf-oswald
    - ttf-quintessential
    - ttf-raleway
    - ttf-signika
    - ttf-spacemono

  media:
    - iscan-plugin-gt-x820  # Epson V600 scanner
    - vlc
    - vdhcoapp-bin  # Video Downloadhelper companion app
    - guvcview  # webcam record
    - gwenview  # best image viewer for KDE
    - libheif
    - [ spotify, zenity ]
    - youtube-dl
    - mediainfo-gui
    - handbrake
    - jhead
  media_extra:
    - calibre  # e-book management
    - losslesscut  # video trim
    - darktable
    # - entangle  # camera tethering
    - flac2all
    - gpscorrelate
    - gthumb
    - kamoso  # webcam recorder from KDE community
    - kindleunpack
    - cava  # sound visualizer
    - [ kdenlive, recordmydesktop ]

  networking:
    - nmap
    - tcpdump
    - trickle
  networking_extra:
    - bind-tools
    - bitmeter-os
    - bmon
    - darkstat  # packet sniffer
    - lftp
    - mtr
    - net-tools
    - nethogs
    - ngrep
    - openvpn
    - pdsh
    - socat
    - speedtest-cli
    - sshuttle
    - whois
    - wireshark-qt
    - wondershaper-git


  office:
    - copyq  # clipboard manager
    - libreoffice-still
    - [jre-openjdk, openaudible-bin]
    - simple-scan
    - masterpdfeditor-free  # Older 4.x version of masterpdfeditor, which I paid for but the key doesn't work and support won't reply
    - [ mpv, meta-group-texlive-most, anki ]  # See Anki setup in Obsidian notes


  printers:
    - brother-hl3170cdw


  sway:
    - vulkan-intel
    - vulkan-icd-loader
    - vulkan-mesa-layers
    - intel-media-driver
    - pipewire-jack

    - wlprop
    - wev

    - sway
    - xorg-xwayland
    - qt5ct  # https://wiki.archlinux.org/index.php/Qt#Configuration_of_Qt5_apps_under_environments_other_than_KDE_Plasma
    - breeze
    - breeze-icons

    - mako
    - swaybg
    - swayidle
    - swaylock
    - waybar
    - j4-dmenu-desktop
    - bemenu
    - bemenu-wayland
    - xdg-desktop-portal-gtk
    - xdg-desktop-portal-wlr
    - otf-font-awesome
    - wdisplays
    - way-displays
    - brightnessctl
    - ddcci-driver-linux-dkms
    - grim
    - slurp
    - wlsunset
    - clipman

    # Dolphin stuff
    - baloo
    - dolphin
    - dolphin-plugins
    - ark  # compresses/extract zip files from within dolphin
    - insync
    - insync-dolphin
    - kdegraphics-thumbnailers  # Image files, PDFs and Blender application files.
    - kimageformats  # Gimp .xcf files
    - libheif  # HEIF files
    - qt6-imageformats  # .webp, .tiff, .tga, .jp2 files
    - resvg  # Fast and accurate SVG image thumbnails
    - ffmpegthumbs  # Video files (based on ffmpeg)
    - kdesdk-thumbnailers  # Plugins for the thumbnailing system
    - raw-thumbnailer  # .raw files
    - taglib  # Audio files previews
    # - kde-thumbnailer-apk  # Android package files
