user:
  name: cgorichanaz
  fullname: Charlie Gorichanaz
  group: cgorichanaz
  email:  charlie@gorichanaz.com
  uid: 1000
  gid: 1000
  shell: /usr/bin/zsh
  layout: dvorak
  # # be sure to change the password after first run
  # password: test
  log:
    dir: log
    rotate: 8
dotfiles:
  git_url: "git://github.com/CNG/dotfiles.git"
  path: dotfiles
  files_to_copy_not_link: "htoprc Preferences.sublime-settings"
ssh_keys:
  - cng1408
  - cng1408s
  - id_rsa

# hostsctl:
#   url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

journal:
  max_size: 5G
ssh:
  port: 22
  # user_key: /root/id_rsa
  enable_sshd: True
udisks:
  auto_mount: True
  shared_mount: True

desktop_environment: sway
flags:
  - dummyflag
  - digikam
  # - server




# TODO

# samba_log: /var/log/samba.log
# samba_log_size: 60000
# gnupg:
#   enable_agent: True
#   emulate_ssh: True
# network:
#   spoof_mac: False
#   conn_check:
#     interval: 0
# fingerprint: False
# localtime:
#   run_on: all
# nameservers:
# - 1.1.1.1
# middle_click_scroll: True
# multitouch: True



packages:
  deprecated:
  base:
    - base-devel
    - man-db
    - man-pages
    - reflector  # For pacman mirror ranking
    - tmux
    - git
    - rsync
    - coreutils
    - dateutils
    - moreutils
    - bc
    - ruby
    - go
    # - kfind
    - lsof
    - strace
    - sysstat
    # - inotify-tools  # For inotifywait
    # - ack
    # - command-not-found  # may need to check if /etc/zsh/zprofile is sourced as it says it should be
    - grc  # Colorize logfiles and command output
    - highlight
    - htop
    - iftop
    - iotop
    - iputils
    - usbutils  # provides lsusb
    - jq
    - yq
    # - linux-headers
    - nfs-utils
    # - ntop
    # - pygmentize  # Python syntax highlighter
    # - qt5-webengine
    # - rsnapshot
    # - screen
    # - solaar
    - sqlitebrowser
    - tree
    # - vagrant
    # - vnstat
    - wget
    # - wireless_tools
    - firefox


  base_aur:
    - alacritty
    - google-chrome
    - upd72020x-fw  # resolve missing firmware warning xhci_pci
    # - ctmg
    # - imwheel
    # - miller
    # - myrepos
    # - neofetch
    # - python-systemd  # Ansible log to journal
    # - tmux-bash-completion
    # - zplug
    # - acpid
    # # Next two were on laptop only, adding here for consistency till I test why
    # - acpitool
    # - acpi_call-dkms
    # - redshift  # blue light reduction

  editors:
    - nano
    - sublime-text
    - vi
    - vim
    # - gvim  # gvim (then don't need vim) required for clipboard/libX11 support
    # - fzf  # fuzzy finder
    # - python-black  # vim-codefmt uses system "black"

  filesystem:
    - dosfstools
    - ntfs-3g
    # - efibootmgr
    # - exfat-utils
    # - hfsprogs
    # no longer avail, check if still needed for mac migration
    # - hfsutils
    # - libguestfs  # mount VMDKs, large install
    # - exfatprogs
    # - gparted
    # - udftools

  fonts:
    # - ttf-nerd-fonts-input  # checksum issue, ugh
    - ttf-opensans
    - adobe-base-14-fonts
    - adobe-source-code-pro-fonts
    - ttf-adobe-source-fonts
    - ttf-fira-code
    - ttf-fira-mono
    - ttf-fira-sans
    - ttf-font-awesome-4
    - ttf-tahoma
    - ttf-ubuntu-font-family
  _TODO_fonts:
    - cantarell-fonts
    - gsfonts
    - noto-fonts
    - terminus-font
    - tex-gyre-fonts
    - ttc-iosevka
    - ttc-iosevka-aile
    - ttc-iosevka-ss08
    - ttf-bitstream-charter
    - ttf-bookerly
    - ttf-caladea
    - ttf-carlito
    - ttf-contemporary
    - ttf-cooper-hewitt
    - ttf-courier-prime
    - ttf-dejavu
    - ttf-droid
    - ttf-fantasque-sans-mono
    - ttf-heuristica
    - ttf-ibm-plex
    - ttf-inconsolata
    - ttf-iosevka
    - ttf-latex-xft-fonts
    - ttf-liberation
    - ttf-mac-fonts
    - ttf-merriweather
    - ttf-merriweather-sans
    - ttf-mplus-git
    - ttf-nanum
    - ttf-oswald
    - ttf-quintessential
    - ttf-raleway
    - ttf-signika
    - ttf-spacemono

  media:
    - iscan-plugin-gt-x820  # Epson V600 scanner
    - vlc
    - vdhcoapp-bin  # Video Downloadhelper companion app
    - guvcview  # webcam record
    - gwenview  # best image viewer for KDE
    - libheif
    - spotify
    - youtube-dl
    - mediainfo-gui
    - handbrake
  media_extra:
    # - [xininfo-git, copyq-git, teiler-git ]  # script for screenshots and screencasts
    # - inkscape
    # - makemkv-cli
    - [ cdparanoia, abcde ]  # CD track encoder
    - [ libraw, libpng, librsvg, openjpeg2, imagemagick ]
    - calibre  # e-book management
    - losslesscut  # video trim
    - darktable
    # - entangle  # camera tethering
    - flac2all
    - flashplugin
    # - flite  # lightweight speech synthesis engine
    # - fritzing  # Haven't used this is a while
    - gpscorrelate
    - gthumb
    # - imv  # Image viewer for X11/Wayland
    - kamoso  # webcam recorder from KDE community
    - kindleunpack
    - cava  # sound visualizer
    # misc media codecs and helpers
    - exiv2
    - flac
    - gst-libav
    # error: failed to commit transaction (conflicting files)
    # - gst-plugins-good
    - lame
    - perl-image-exiftool
    - x264
    - [ kdenlive, recordmydesktop ]

  networking:
    - nmap
    - tcpdump
    - trickle
  networking_extra:
    - bind-tools
    - bitmeter-os
    - bmon
    - darkstat  # packet sniffer
    - lftp
    - mtr
    - net-tools
    - nethogs
    - ngrep
    - openssh
    - openvpn
    - pdsh
    - socat
    - speedtest-cli
    - sshuttle
    - whois
    - wireshark-qt
    - wmsystemtray
    - wondershaper-git

  office:
    - copyq  # clipboard manager
  _TODO_office:
    - archlinux-java-run
    - automatic
    # - cerebro
    - enscript
    - [ insync, insync-dolphin ]
    - libreoffice-fresh
    - masterpdfeditor
    # - okular  # Ebook Reader, simple yet capable
    - pandoc
    - pdfgrep
    - simple-scan
    - task  # TaskWarrior
    - visidata
    - zathura-pdf-mupdf
    - zathura-ps
    - [ gmp, mpfr, libmpc, isl, mplayer, texlive-core, texlive-latexextra, anki ]
    # Anki addons:
    # not yet Anki 2.1: 162313389 Power format pack
    # but this has some funcs: 295889520 Mini Format Pack
    # 874215009 Advanced Browser
    # 1672832404 Add note id
    # 613684242 True retention
    # 3491767031 Multi-column note editor
    # 291119185 Batch Note Editing
    # 1788670778 CrowdAnki comprehensive JSON representation to facilitate collaboration
    # 117604477 Dark Themes Fix for 2.0

  printers:
    - brother-hl3170cdw


  sway:
    - pipewire-jack
    - sway
    - mako
    - swaybg
    - swayidle
    - swaylock
    - waybar
    - j4-dmenu-desktop
    - bemenu
    - xorg-xwayland
    - xdg-desktop-portal-gtk
    - xdg-desktop-portal-wlr
    - otf-font-awesome
    - wdisplays
    - brightnessctl
    - ddcci-driver-linux-dkms
    - grim
    - slurp
    - wlsunset
    # - rofi  # menu
    # req by waybar - playerctl  # media player controls
    - qt5ct  # https://wiki.archlinux.org/index.php/Qt#Configuration_of_Qt5_apps_under_environments_other_than_KDE_Plasma


  _TODO_i3:
    - feh  # Set background
    - [ gnome-themes-extra, gtk-engines ]  # fixed Spotify Gtk error
    - [ kwallet, kwalletmanager ]
    - ark  # compresses/extract zip files from within dolphin
    - xcape  # Configure modifier keys to act as other keys when pressed and released on their own
    - xclip  # Used for Rofi cheatsheet/notes
    - xorg-xinput
    - scrot
    - escrotum-git
    - [ breeze, breeze-icons ]
    - [ ffmpegthumbnailer, ffmpegthumbnailer-mp3 ]  # opt dept Nemo
    - lxappearance  # maybe, was trying to change GTK3 theme with this tool
    - [ dolphin, dolphin-plugins, insync-dolphin, kdegraphics-thumbnailers, kimageformats, qt5-imageformats, resvg, ffmpegthumbs, kdesdk-thumbnailers, raw-thumbnailer, taglib ]  # This might be temporary, mem leak issues with Nemo
    # canta-icon-theme stopped working, I don't recall if I actually needed it
    # here...
    # - [ canta-gtk-theme, numix-circle-icon-theme-git, canta-icon-theme ]
    - [ canta-gtk-theme, numix-circle-icon-theme-git ]

  plasma:
    - TODO
