---
- name: Install net tools
  aur:
    name: "{{ item }}"
  become: yes
  become_user: aur_builder
  with_items: "{{ packages.nettools }}"

- name: Add user to wireshark group
  user:
    name: "{{ user.name }}"
    groups: wireshark
    append: yes
