# https://github.com/jwilm/alacritty/blob/master/alacritty.yml
env:
  # Changing this from "alacritty" to "xterm-256color" is required to get 24 bit
  # color working inside Tmux. (What do we lose?)
  TERM: xterm-256color
  # OK let's try setting this in the env passed to Tmux instead, when I get
  # a chance to review how I'm launching Tmux with SystemD etc.
  # TERM: alacritty
window:
  dimensions:
    columns: 0
    lines: 0
  padding:
    x: 5
    y: 5
  decorations: none
  dynamic_title: true
  opacity: 0.8
scrolling:
  history: 0
  multiplier: 0
font:
  normal:
    family: &family Input Mono
    # family: &family MesloLGS NF
    style: Regular
  bold:
    family: *family
    style: Bold
  italic:
    family: *family
    style: Italic
  size: 14.0
bell:
  animation: EaseOutExpo
  duration: 5
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }
mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: false
  faux_scrolling_lines: 1
selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
cursor:
  # style: Beam|Underline|[Block]
  style: Underline
  unfocused_hollow: true
live_config_reload: true

# If the same trigger is assigned to multiple actions, all of them are executed
# at once.
key_bindings:
  - { key: Paste,                                action: Paste          }
  - { key: Copy,                                 action: Copy           }
  - { key: L,         mods: Shift|Control,       action: ClearLogNotice }
  - { key: PageUp,    mods: Shift,   mode: ~Alt, action: ScrollPageUp,  }
  - { key: PageDown,  mods: Shift,   mode: ~Alt, action: ScrollPageDown }
  - { key: Home,      mods: Shift,   mode: ~Alt, action: ScrollToTop,   }
  - { key: End,       mods: Shift,   mode: ~Alt, action: ScrollToBottom }

  - { key: V,        mods: Control|Shift,           action: Paste            }
  - { key: C,        mods: Control|Shift,           action: Copy             }
  - { key: Insert,   mods: Shift,                   action: PasteSelection   }
  - { key: Key0,     mods: Control,                 action: ResetFontSize    }
  - { key: Equals,   mods: Control,                 action: IncreaseFontSize }
  - { key: Plus,      mods: Control,                 action: IncreaseFontSize }
  - { key: Minus,    mods: Control,                 action: DecreaseFontSize }

schemes:
  # Colors (Solarized Light)
  solarized_light: &light
    # Default colors
    primary:
      background: '#fdf6e3' # base3
      foreground: '#657b83' # base00

    # Cursor colors
    cursor:
      text:   '#fdf6e3' # base3
      cursor: '#657b83' # base00

    # Normal colors
    normal:
      black:   '#073642' # base02
      red:     '#dc322f' # red
      green:   '#859900' # green
      yellow:  '#b58900' # yellow
      blue:    '#268bd2' # blue
      magenta: '#d33682' # magenta
      cyan:    '#2aa198' # cyan
      white:   '#eee8d5' # base2

    # Bright colors
    bright:
      black:   '#002b36' # base03
      red:     '#cb4b16' # orange
      green:   '#586e75' # base01
      yellow:  '#657b83' # base00
      blue:    '#839496' # base0
      magenta: '#6c71c4' # violet
      cyan:    '#93a1a1' # base1
      white:   '#fdf6e3' # base3

  # Colors (Solarized Dark)
  solarized_dark: &dark
    # Default colors
    primary:
      background: '#002b36' # base03
      foreground: '#839496' # base0

    # Cursor colors
    cursor:
      text:   '#002b36' # base03
      cursor: '#839496' # base0

    # Normal colors
    normal:
      black:   '#073642' # base02
      red:     '#dc322f' # red
      green:   '#859900' # green
      yellow:  '#b58900' # yellow
      blue:    '#268bd2' # blue
      magenta: '#d33682' # magenta
      cyan:    '#2aa198' # cyan
      white:   '#eee8d5' # base2

    # Bright colors
    bright:
      black:   '#586e75' # base01
      red:     '#cb4b16' # orange
      green:   '#586e75' # base01
      yellow:  '#657b83' # base00
      blue:    '#839496' # base0
      magenta: '#6c71c4' # violet
      cyan:    '#93a1a1' # base1
      white:   '#fdf6e3' # base3

  # Colors (Monokai Pro)
  monokai_pro: &monokai_pro
    # Default colors
    primary:
      background: '#2D2A2E'
      foreground: '#FCFCFA'

    # Normal colors
    normal:
      black:   '#403E41'
      red:     '#FF6188'
      green:   '#A9DC76'
      yellow:  '#FFD866'
      blue:    '#FC9867'
      magenta: '#AB9DF2'
      cyan:    '#78DCE8'
      white:   '#FCFCFA'

    # Bright colors
    bright:
      black:   '#727072'
      red:     '#FF6188'
      green:   '#A9DC76'
      yellow:  '#FFD866'
      blue:    '#FC9867'
      magenta: '#AB9DF2'
      cyan:    '#78DCE8'
      white:   '#FCFCFA'


  charlie_monokai: &charlie
    primary:
      background: '0x00002c'
      foreground: '0xeaeaea'
    normal:
      black:   '0x1B1D1E'
      red:     '0xFF0044'
      green:   '0x82B414'
      yellow:  '0xFD971F'
      blue:    '0x266C98'
      magenta: '0xAC0CB1'
      cyan:    '0xAE81FF'
      white:   '0xCCCCCC'
    bright:
      black:   '0x808080'
      red:     '0xF92672'
      green:   '0xA6E22E'
      yellow:  '0xE6DB74'
      blue:    '0x7070F0'
      magenta: '0xD63AE1'
      cyan:    '0x66D9EF'
      white:   '0xF8F8F2'

colors: *charlie
draw_bold_text_with_bright_colors: false
