live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 5

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x808080"
blue = "0x7070F0"
cyan = "0x66D9EF"
green = "0xA6E22E"
magenta = "0xD63AE1"
red = "0xF92672"
white = "0xF8F8F2"
yellow = "0xE6DB74"

[colors.normal]
black = "0x1B1D1E"
blue = "0x266C98"
cyan = "0xAE81FF"
green = "0x82B414"
magenta = "0xAC0CB1"
red = "0xFF0044"
white = "0xCCCCCC"
yellow = "0xFD971F"

[colors.primary]
background = "0x00002c"
foreground = "0xeaeaea"

[cursor]
style = "Underline"
unfocused_hollow = true

[env]
TERM = "alacritty"

[font]
size = 14.0

[font.bold]
family = "Source Code VF"
style = "Bold"

[font.italic]
family = "Source Code VF"
style = "Italic"

[font.normal]
family = "Source Code VF"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 0
multiplier = 0

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "none"
dynamic_title = true
opacity = 0.8

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 5
y = 5
