#!/usr/bin/env zsh

# This lets you quickly jump into a project directory.
#
# Type:
#
#   c <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_c`. Typical use:
#
#    c holm<tab>/bo<tab>
#
# ...to quickly jump into holman/boom, for example.
#
# This also accounts for how Go structures its projects. For example, it will
# autocomplete both on $PROJECTS, and also assume you want to autocomplete on
# your Go projects in $GOPATH/src.

if [ ! -z "$1" ]; then
  if [[ $GOPATH ]] && [[ -s $GOPATH/src/github.com/$1 ]]; then
    cd "$GOPATH/src/github.com/$1"
  elif [[ -s $HOME/Workspace/$1 ]]; then
    cd "$HOME/Workspace/$1"
  elif [[ $PROJECTS ]]; then
    cd "$PROJECTS/$1"
  else
    cd "$HOME/$1"
  fi
else
  if [[ -d ~/Workspace ]]; then
    cd ~/Workspace
  elif [[ $PROJECTS ]]; then
    cd "$PROJECTS"
  else
    cd
  fi
fi
