#!/bin/sh

# https://github.com/mathiasbynens/dotfiles/blob/master/.functions

# `s` with no arguments opens the current directory in Sublime Text, otherwise
# opens the given location

if [ $# -eq 0 ]; then
	subl3 .;
else
	subl3 "$@";
fi;
