#!/usr/bin/env bash

logger () {
  echo -e "$(date --utc '+%Y-%m-%d %H:%M:%S')\t$@" | tee -a $HOME/timetracking.txt
  echo "$@" | systemd-cat -t $(basename $0)
}
logger "$@"

command task "$@"
pkill -RTMIN+10 i3blocks

