# ~/.xprofile runs first, before xmodmap
# ~/.xsession runs last in /etc/lightdm/Xsession
# errors logged to ~/.xsession-errors
set -x

logger () {
  echo "$@" | systemd-cat -t $(basename $0)
}

QT_STYLE_OVERRIDE=kvantum
# export QT_QPA_PLATFORMTHEME=qt5ct
# didn't test next two yet
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCALE_FACTOR=1

# This definitely gets reset sometimes, possibly after connecting monitor/dock
# or after suspend, but likely the former as I don't suspend often. It seemed to
# be getting reset to the value in ansible/roles/lightdm/files/50-lightdm.conf
xset r rate 444 44

#xset -dpms

libinput-gestures-setup start &

if ! pgrep imwheel; then
  imwheel --buttons "45" &
fi

if pgrep xbindkeys; then pkill -9 xbindkeys; fi
xbindkeys &

if pgrep xmodmap; then pkill -9 xmodmap; fi
xmodmap ~/.Xmodmap

~/.local/bin/autolock &

# custom script to handle lid open/close, maybe more
if ! pgrep acpi_socket; then
  ~/.local/bin/acpi_socket &
fi
