---
# Optional dependencies for foldingathome
#     clinfo: for folding with an NVIDIA GPU
#     cuda: for folding with an NVIDIA GPU [installed]
#     ocl-icd: for folding with any GPU [installed]
#     opencl-driver: for folding with any GPU [installed]
- name: Remove deprecated packages
  pacman:
    name:
      - fahcontrol-beta
      - fahviewer-beta
      - foldingathome-beta
      - opencl-icd-loader
    state: absent
  become: yes

- name: Install Folding@Home software
  block:
    - aur:
        name: "{{ item }}"
      with_items:
        - foldingathome
        - fahcontrol
        - fahviewer
    - aur:
        name: "{{ item }}"
      with_items:
        - ocl-icd
        - opencl-nvidia
        - cuda
        - clinfo
      when: foldingathome.num_gpus is defined and foldingathome.num_gpus > 0
  become: yes
  become_user: aur_builder

- name: Setup Folding@Home
  block:
    - name: Configure Folding@Home
      template:
        src: config.xml.j2
        dest: /etc/foldingathome/config.xml
      become: yes
    - name: Remove custom Folding@Home timer service
      file:
        name: "{{ item }}"
        state: absent
      become: yes
      with_items:
        - /opt/fah
        - /etc/systemd/system/foldingathome.service.d
        - /etc/systemd/system/foldingathome-idle-check.service
        - /etc/systemd/system/foldingathome-idle-check.timer
  when: foldingathome.simplified_config is defined and foldingathome.simplified_config

- name: Setup Folding@Home
  template:
    src: config.xml.j2
    dest: /opt/fah/config.xml
  become: yes
  become: yes
  when: foldingathome.simplified_config is not defined or not foldingathome.simplified_config

- name: Patch Folding@Home service to start idle timer
  block:
    - name: Install idle checker script
      copy:
        src: fah-idle-check
        dest: "/usr/local/bin/fah-idle-check"
        mode: 0755
    - name: Create service to run the idle checker script
      copy:
        src: foldingathome-idle-check.service
        dest: /etc/systemd/system/foldingathome-idle-check.service
        mode: 0644
    - name: Create timer to launch the idle checker service
      copy:
        src: foldingathome-idle-check.timer
        dest: /etc/systemd/system/foldingathome-idle-check.timer
        mode: 0644
    - name: Create directory
      file:
        name: /etc/systemd/system/foldingathome.service.d
        state: directory
        mode: 0755
    - name: Copy Systemd unit file
      copy:
        src: foldingathome.override.conf
        dest: /etc/systemd/system/foldingathome.service.d/override.conf
        mode: 0644
      notify:
        - reload systemd config
        - reload foldingathome
  become: yes
  when: foldingathome.simplified_config is not defined or not foldingathome.simplified_config

- name: Enable and start Folding@Home service
  service:
    name: foldingathome
    enabled: yes
    state: started

- name: Enable and start Folding@Home NVIDIA service
  service:
    name: foldingathome-nvidia
    enabled: yes
    state: started
  become: yes
