---
- name: Install acpi_call for TLP battery functions
  pacman:
    name: acpi_call-dkms
    state: present

- name: Install tpacpi-bat
  pacman:
    name: tpacpi-bat
    state: present

- name: Install firmware update utility
  pacman:
    name: fwupd
    state: present

- name: Get firmware updates
  command: fwupdmgr refresh

- name: Update firmware
  command: fwupdmgr update --force
  become: yes
