---
- name: Install i3
  pacman: name=i3 state=present

- name: Install py3status
  aur: name=py3status user={{ user.name }}
  tags:
    - aur

- name: Verify that default applications file exists
  file: path=/etc/xdg/mimeapps.list state=touch
  tags:
    - debug

- name: Verify header in default applications file
  lineinfile: dest=/etc/xdg/mimeapps.list
              state=present
              line='[Default Applications]'
              insertbefore=BOF
  tags:
      - debug

- include: rofi.yml
