---
- name: Download rofi
  command: cower -dq rofi-git
           chdir=/home/{{ user.name }}/{{ aur.dir }}
           creates=/home/{{ user.name }}/{{ aur.dir }}/rofi-git
  tags:
    - aur
  become: yes
  become_user: "{{ user.name }}"

- name: Build and install rofi
  command: "{{ aur.makepkg }} chdir=/home/{{ user.name }}/{{ aur.dir }}/rofi-git"
  tags:
    - aur
  become: yes
  become_user: "{{ user.name }}"

- name: Download rofi-pass
  command: cower -dq rofi-pass-git
           chdir=/home/{{ user.name }}/{{ aur.dir }}
           creates=/home/{{ user.name }}/{{ aur.dir }}/rofi-pass-git
  tags:
    - aur
  become: yes
  become_user: "{{ user.name }}"

- name: Build and install rofi-pass
  command: "{{ aur.makepkg }} chdir=/home/{{ user.name }}/{{ aur.dir }}/rofi-pass-git"
  tags:
    - aur
  become: yes
  become_user: "{{ user.name }}"

- name: Install i3-wm for rofi window switching
  pacman: name=i3-wm state=present

- name: Download teiler (rofi screenshot app)
  command: cower -dq teiler-git
           chdir=/home/{{ user.name }}/{{ aur.dir }}
           creates=/home/{{ user.name }}/{{ aur.dir }}/teiler-git
  tags:
    - aur
  become: yes
  become_user: "{{ user.name }}"

- name: Build and install teiler
  command: "{{ aur.makepkg }} chdir=/home/{{ user.name }}/{{ aur.dir }}/teiler-git"
  tags:
    - aur
  become: yes
  become_user: "{{ user.name }}"

- name: Download copyq (clipboard mgr)
  command: cower -dq copyq-git
           chdir=/home/{{ user.name }}/{{ aur.dir }}
           creates=/home/{{ user.name }}/{{ aur.dir }}/copyq-git
  tags:
    - aur
  become: yes
  become_user: "{{ user.name }}"

- name: Build and install copyq
  command: "{{ aur.makepkg }} chdir=/home/{{ user.name }}/{{ aur.dir }}/copyq-git"
  tags:
    - aur
  become: yes
  become_user: "{{ user.name }}"
