---
- name: Install vagrant
  pacman: name=vagrant state=present

- name: Install consul
  pacman: name=consul state=present

- name: Install vault
  aur: name={{ item }} user={{ user.name }}
  with_items:
    - vault-bin
  tags:
    - aur
