---
- name: Install keymaps, fonts, charset maps for kbd
  apt:
    name: console-data

- name: Enable dvorak for XOrg libinput
  copy:
    src: 40-libinput-dvorak.conf
    dest: /etc/X11/xorg.conf.d/40-libinput-dvorak.conf

- name: Add control-caps dvorak keymap
  copy:
    src: dvorak-cc.map.gz
    dest: /usr/share/keymaps/i386/dvorak/dvorak-cc.kmap.gz

- name: Set key layout in vconsole
  lineinfile:
    dest: /etc/vconsole.conf
    regexp: "^KEYMAP="
    state: present
    line: "KEYMAP={{ user.layout }}-cc"

# do we need anything in /etc/default/keyboard?
### XKBMODEL="pc105,pc105"
# XKBLAYOUT="us,us"
# XKBVARIANT="dvorak,"
