---
- name: Install TLP
  pacman:
    name:
      - x86_energy_perf_policy
      - ethtool
      - tlp
      - tlp-rdw
    state: present

- name: Copy TLP configuration file
  copy:
    src: tlp.conf
    dest: /etc/default/tlp
  notify:
    - restart tlp

- name: Mask systemd radio service
  command: systemctl mask systemd-rfkill

- name: Enable TLP
  service:
    name: tlp
    enabled: yes

- name: Enable TLP sleep
  service:
    name: tlp-sleep
    enabled: yes
