---
- name: Install TLP
  pacman:
    name:
      - x86_energy_perf_policy
      - ethtool
      - tlp
      - tlp-rdw
    state: present

- name: Copy TLP configuration file
  copy:
    src: tlp.conf
    dest: /etc/default/tlp
  notify:
    - restart tlp

# per https://wiki.archlinux.org/index.php/TLP
- name: Mask systemd radio service
  systemd:
    name: systemd-rfkill
    masked: yes
- name: Mask systemd radio socket
  systemd:
    name: systemd-rfkill.socket
    masked: yes

- name: Enable TLP
  service:
    name: tlp
    enabled: yes

- name: Enable TLP sleep
  service:
    name: tlp-sleep
    enabled: yes

# TODO: Limit this to specific laptops? Was in XPS before, maybe all Dell
- name: Fix thermal throttling limits
  block:
    - name: Install throttled package
      aur:
        name: throttled
      become: yes
      become_user: aur_builder
    - name: Enable throttling service
      service:
        name: lenovo_fix
        enabled: yes
        state: started

- name: Install acpi_call for TLP battery functions
  pacman:
    name: acpi_call-dkms
    state: present

- name: Install tpacpi-bat
  pacman:
    name: tpacpi-bat
    state: present

