#!/bin/sh

# https://github.com/mathiasbynens/dotfiles/blob/master/.functions

# Create a git.io short URL

if [ -z "${1}" -o -z "${2}" ]; then
	echo "Usage: \`gitio slug url\`";
	return 1;
fi;
curl -i https://git.io/ -F "url=${2}" -F "code=${1}";
