#!/bin/sh

# https://github.com/mathiasbynens/dotfiles/blob/master/.functions

# Decode \x{ABCD}-style Unicode escape sequences

perl -e "binmode(STDOUT, ':utf8'); print \"$@\"";
# print a newline unless we’re piping the output to another program
if [ -t 1 ]; then
	echo ""; # newline
fi;
