---
- name: Install rcm
  aur:
    name: rcm
  when: dotfiles is defined
  become: yes
  become_user: aur_builder

# This would put the dotfiles in place for rcup to do its work
# But till I have the repo set up, I need to manually put the
# dotfiles in ~/projects/
# This is extra confusing because I have the dotfiles in GDrive/Projects too
- name: Clone user dotfiles
  git:
    repo: "{{ dotfiles.url }}"
    dest: "/home/{{ user.name }}/{{ dotfiles.source }}"
    accept_hostkey: yes
    update: no
  when: dotfiles.url is defined
  become: yes
  become_user: "{{ user.name }}"

- name: Install user dotfiles
  command: "rcup -U bin -d /home/{{ user.name }}/{{ dotfiles.source }}/files {{ dotfiles.rcup_flags }}"
  when: dotfiles.source is defined
  become: yes
  become_user: "{{ user.name }}"

- name: Set Github author name
  git_config:
    name: user.name
    scope: global
    value: "{{ user.fullname }}"

- name: Set Github author email
  git_config:
    name: user.email
    scope: global
    value: "{{ user.email }}"

- name: Mount volumes
  when: volumes is defined
  block:
  - name: Get device UUIDs
    command: "ls /dev/disk/by-uuid"
    register: ls_result
    changed_when: False
  - set_fact:
      uuids: "{{ ls_result.stdout_lines }}"
  - debug:
      var: uuids
      verbosity: 2
  - name: Mount volumes
    when: item.uuid in uuids
    block:
    - debug:
        msg: "Looking for UUID {{ item.uuid }} in {{ uuids }}"
        verbosity: 2
      with_items: "{{ volumes }}"
    - name: Mount volumes
      mount:
        path: "{{ item.path }}"
        src: "UUID={{ item.uuid }}"
        fstype: auto
        opts: "{{ item.opts }}"
        state: mounted
      with_items: "{{ volumes }}"

- name: Link private files
  file:
    path: "/home/{{ user.name }}/.{{ item }}"
    src: "/home/{{ user.name }}/projects/dotfiles/private/{{ item }}"
    state: link
    force: yes
  with_items:
    - zshrc.local
    - zshenv.local
    - gitconfig.local
    - ssh
