---
- name: Install rcm
  aur:
    name: rcm
  when: dotfiles is defined
  become: yes
  become_user: aur_builder

# This would put the dotfiles in place for rcup to do its work
# But till I have the repo set up, I need to manually put the
# dotfiles in ~/projects/
# This is extra confusing because I have the dotfiles in GDrive/Projects too
- name: Clone user dotfiles
  git:
    repo: "{{ dotfiles.url }}"
    dest: "/home/{{ user.name }}/{{ dotfiles.source }}"
    accept_hostkey: yes
    update: no
  when: dotfiles.url is defined
  become: yes
  become_user: "{{ user.name }}"

- name: Set .config ownership
  file:
    dest: "{{ item }}"
    owner: "{{ user.name}}"
    group: "{{ user.name}}"
    recurse: yes
  with_items:
    - "/home/{{ user.name }}/.config"
  become: yes

- name: Install user dotfiles
  when: dotfiles.source is defined
  shell: "rcup -U bin -d /home/{{ user.name }}/{{ dotfiles.source }}/files -fv | grep -v '^identical'"
  environment:
    COPY_ALWAYS: "{{ dotfiles.files_to_copy_not_link }}"
  become: yes
  become_user: "{{ user.name }}"
  register: result
  changed_when: result.rc == 0  # grep got results
  failed_when: result.rc > 1  # grep return 1 is not an error
- name: "Made the following dotfiles changes:"
  debug:
    msg: "{{ result.stdout_lines }}"
  when: result.rc == 0
  changed_when: result.rc == 0  # grep got results

- name: Set Github author name
  git_config:
    name: user.name
    scope: global
    value: "{{ user.fullname }}"

- name: Set Github author email
  git_config:
    name: user.email
    scope: global
    value: "{{ user.email }}"

- name: Mount volumes
  when: volumes is defined
  block:
  - name: Get device UUIDs
    command: "ls /dev/disk/by-uuid"
    register: ls_result
    changed_when: False
  - set_fact:
      uuids: "{{ ls_result.stdout_lines }}"
  - debug:
      var: uuids
      verbosity: 2
  - name: Mount volumes
    when: item.uuid in uuids
    block:
    - debug:
        msg: "Looking for UUID {{ item.uuid }} in {{ uuids }}"
        verbosity: 2
      with_items: "{{ volumes }}"
    - name: Mount volumes
      mount:
        path: "{{ item.path }}"
        src: "UUID={{ item.uuid }}"
        fstype: auto
        opts: "{{ item.opts }}"
        state: mounted
      with_items: "{{ volumes }}"

- name: Link private files
  file:
    path: "/home/{{ user.name }}/.{{ item }}"
    src: "/home/{{ user.name }}/projects/dotfiles/private/{{ item }}"
    state: link
    force: yes
  with_items:
    - zshrc.local
    - zshenv.local
    - gitconfig.local
    - ssh
