---
- name: Install rcm
  aur:
    name: rcm
  when: dotfiles is defined
  become: yes
  become_user: aur_builder

# This would put the dotfiles in place for rcup to do its work
# But till I have the repo set up, I need to manually put the
# dotfiles in ~/dotfiles
- name: Clone user dotfiles
  git:
    repo: "{{ dotfiles.git_url }}"
    dest: "/home/{{ user.name }}/{{ dotfiles.path }}"
    accept_hostkey: yes
    update: no
  when: dotfiles.url is defined
  become: yes
  become_user: "{{ user.name }}"

- name: Install user dotfiles
  when: dotfiles.path is defined
  shell: "rcup -d /home/{{ user.name }}/{{ dotfiles.path }}/files -fv | grep -v '^identical'"
  environment:
    COPY_ALWAYS: "{{ dotfiles.files_to_copy_not_link }}"
  become: yes
  become_user: "{{ user.name }}"
  register: result
  changed_when: result.rc == 0  # grep got results
  failed_when: result.rc > 1  # grep return 1 is not an error
- name: "Made the following dotfiles changes:"
  debug:
    msg: "{{ result.stdout_lines }}"
  when: result.rc == 0
  changed_when: result.rc == 0  # grep got results

- name: Set Github author name
  git_config:
    name: user.name
    scope: global
    value: "{{ user.fullname }}"

- name: Set Github author email
  git_config:
    name: user.email
    scope: global
    value: "{{ user.email }}"

- name: Mount volumes
  when: volumes is defined
  block:
  - name: Get device UUIDs
    command: "ls /dev/disk/by-uuid"
    register: ls_result
    changed_when: False
  - set_fact:
      uuids: "{{ ls_result.stdout_lines }}"
  - debug:
      var: uuids
      verbosity: 2
  - name: Mount volumes
    when: item.uuid in uuids
    block:
    - debug:
        msg: "Looking for UUID {{ item.uuid }} in {{ uuids }}"
        verbosity: 2
      with_items: "{{ volumes }}"
    - name: Mount volumes
      mount:
        path: "{{ item.path }}"
        src: "UUID={{ item.uuid }}"
        fstype: auto
        opts: "{{ item.opts }}"
        state: mounted
      with_items: "{{ volumes }}"

- name: Link private files
  file:
    path: "/home/{{ user.name }}/.{{ item }}"
    src: "/home/{{ user.name }}/{{ dotfiles.path }}/private/{{ item }}"
    state: link
    force: yes
  with_items:
    - zshrc.local
    - zshenv.local
    - gitconfig.local
    - ssh

# # TODO this is still clunky, and work's Workspace is huge
# - name: Set user files ownership in case we created files as root
#   file:
#     path: "/home/{{ user.name }}"
#     owner: "{{ user.name}}"
#     group: "{{ user.name}}"
#     # set directories to 755, and files to 644
#     mode: "u=rwX,g=rX,o=rX"
#     recurse: yes
#     follow: no
#   become: yes

- name: Reduce permissions on .ssh keys
  file:
    path: "/home/{{ user.name }}/.ssh/{{ item }}"
    mode: 0600
  with_items: "{{ ssh_keys }}"
  become: yes
