---
- name: Install wormhole
  when: "'wormhole' in roles"
  block:
  - name: Install magic-wormhole
    aur:
      name: "{{ item }}"
    with_items:
      - python-hkdf
      - python-spake2
      - python-ipaddress
      - python-txtorcon
      - magic-wormhole
  - name: Setup wormhole firejail
    when: "'firejail' in roles"
    block:
    - name: Jail magic-wormhole
      file:
        src: /usr/bin/firejail
        dest: /usr/local/bin/wormhole
        state: link
    - name: Push magic-wormhole firejail profile
      file:
        src: firejail/wormhole.profile
        dest: /usr/local/etc/firejail/wormhole.profile
      notify:
        - activate firejail profiles

- name: Remove magic-wormhole
  when: "'wormhole' not in roles"
  pacman:
    state: absent
    name:
      - python-hkdf
      - python-spake2
      - python-ipaddress
      - python-txtorcon
      - magic-wormhole

- name: Remove wormhole firejail
  when: "'firejail' not in roles"
  block:
  - name: Unjail magic-wormhole
    file:
      path: /usr/local/bin/wormhole
      state: absent
  - name: Remove magic-wormhole firejail profile
    file:
      path: /usr/local/etc/firejail/wormhole.profile
      state: absent
