---
- name: Install magic-wormhole
  aur: name={{ item }}
  with_items:
      - python-hkdf
      - python-spake2
      - python-ipaddress
      - python-txtorcon
      - magic-wormhole

- name: Jail magic-wormhole
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/wormhole
        state=link

- name: Push magic-wormhole firejail profile
  copy: src=firejail/wormhole.profile dest=/usr/local/etc/firejail/wormhole.profile
  notify:
    - activate firejail profiles
