---
- name: Install Tor
  pacman:
    state: present
    name:
      - tor
      - torsocks

- name: Set Tor to run as tor
  lineinfile:
    dest: /etc/tor/torrc
    regexp: "^User"
    state: present
    line: "User tor"

- name: Create Tor systemd unit file directory
  file:
    path: /etc/systemd/system/tor.service.d
    state: directory

- name: Push Tor socket unit file
  copy:
    src: tor-service-override.conf
    dest: /etc/systemd/system/tor.service.d/override.conf
  notify:
    - reload systemd config

- name: Verify Tor firejail local profile exists
  file:
    path: /etc/firejail/tor.local
    state: touch

- name: Allow Tor firejail /dev access
  lineinfile:
    dest: /etc/firejail/tor.local
    line: "ignore private-dev"

- name: Enable and start Tor
  service:
    name: tor
    enabled: yes
    state: started
  when: tor.run_on == "all"

- name: Remove Tor from trusted unit list
  lineinfile:
    dest: /usr/local/etc/trusted_units
    state: absent
    line: tor.service
  when: tor.run_on == "all"

- name: Disable Tor
  service:
    name: tor
    enabled: no
  when: tor.run_on == "trusted"

- name: Add Tor to trusted unit list
  lineinfile:
    dest: /usr/local/etc/trusted_units
    state: present
    line: tor.service
  when: tor.run_on == "trusted"
