---
- name: Install fingerprint package fprintd
  pacman:
    name: fprintd
    state: present

- name: Push fingerprint sudo authentication file
  template:
    src: pam.d/sudo.j2
    dest: /etc/pam.d/sudo

- name: Push trackpoint udev rules
  copy:
    src: 10-trackpoint.rules
    dest: /etc/udev/rules.d/10-trackpoint.rules
