---
- name: Install Chromium
  pacman: name=chromium state=present
  tags:
    - chromium

- name: Jail Chromium
  copy: src=chromium.sh dest=/usr/local/bin/chromium mode=0755
  tags:
    - chromium
    - firejail

- name: Install Chromium Pepper Flash
  aur: name=chromium-pepper-flash user={{ user.name }}
  tags:
    - aur
    - chromium
