---
- name: Install Chromium
  pacman: name=chromium state=present
  tags:
    - chromium

- name: Jail Chromium
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/chromium
        state=link
  tags:
    - chromium
    - firejail

- name: Install Chromium Pepper Flash
  aur: name=chromium-pepper-flash user={{ user.name }}
  tags:
    - aur
    - chromium
