---
- name: Install Firefox
  pacman: name=firefox state=present
  tags:
    - firefox

- name: Jail Firefox
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/firefox
        state=link
  tags:
    - firefox
    - firejail
