---
- name: Install w3m
  pacman: name=w3m state=present

- name: Install Firefox
  pacman: name=firefox state=present
  tags:
    - firefox

- name: Jail Firefox
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/firefox
        state=link
  tags:
    - firefox
    - firejail

- name: Push Firefox firejail profile
  copy: src=firejail/firefox.profile dest=/usr/local/etc/firejail/firefox.profile
  tags:
    - firefox
    - firejail

- name: Install Chromium
  pacman: name=chromium state=present
  tags:
    - chromium

- name: Jail Chromium
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/chromium
        state=link
  tags:
    - chromium
    - firejail

- name: Push Chromium firejail profile
  copy: src=firejail/chromium.profile dest=/usr/local/etc/firejail/chromium.profile
  tags:
    - chromium
    - firejail

- name: Install Chromium Pepper Flash
  aur: name=chromium-pepper-flash user={{ user.name }}
  tags:
    - aur
    - chromium

- name: Install tor-browser-en
  aur: name=tor-browser-en user={{ user.name }}
  tags:
    - tor-browser
    - aur

- name: Jail tor-browser-en
  copy: src=tor-browser-en.sh dest=/usr/local/bin/tor-browser-en mode=0755
  tags:
    - tor-browser
    - firejail
    - grsec

- name: Push rofi browser chooser
  template: src=browser.sh.j2 dest=/usr/local/bin/browser mode=0755
  tags:
    - rofi
    - chooser

- name: Create local desktop application dir
  file: path=/usr/local/share/applications state=directory
  tags:
    - rofi
    - chooser

- name: Push rofi browser chooser desktop file
  copy: src=browser.desktop dest=/usr/local/share/applications/browser.desktop
  tags:
    - rofi
    - chooser

- name: Set rofi browser chooser as default application for relevant mimetypes
  copy: src=mimeapps.list dest=/etc/xdg/mimeapps.list
  tags:
    - rofi
    - chooser
