---
- name: Install CUPS and drivers
  aur:
    name: "{{ item }}"
  become: yes
  become_user: aur_builder
  with_flattened:
    - ghostscript
    - gsfonts
    - cups
    - cups-pdf
    - gutenprint
    - hplip
    - gtk3-print-backends
    - cups-pk-helper # for PolicyKit to allow nonadmins to edit printers
    - "{{ packages.printers }}"

- name: Allow wheel group to admin printers
  become: yes
  copy:
    src: 49-allow-passwordless-printer-admin.rules
    dest: /etc/polkit-1/rules.d/49-allow-passwordless-printer-admin.rules
    mode: 0644

# Switching out @pigmonkey's approach for wheel/systemd

# - name: Add a print admin group
#   group:
#     name: printadmin
#     state: present

# - name: Add the user to the print and print admin groups
#   user:
#     name: "{{ user.name }}"
#     groups: "printadmin,lp"
#     append: yes

# - name: Allow the print admin group to administer CUPS
#   lineinfile:
#     dest: "/etc/cups/cups-files.conf"
#     regexp: "^SystemGroup"
#     state: present
#     line: "SystemGroup sys root printadmin"
#   notify:
#     - restart cups

- name: Print PDFs to Downloads directory
  become: yes
  lineinfile:
    dest: /etc/cups/cups-pdf.conf
    regexp: "^#? ?Out "
    state: present
    line: "Out ${HOME}/Downloads"
  notify: restart cups

- name: Send CUPS logs to systemd journal
  become: yes
  lineinfile:
    dest: /etc/cups/cups-files.conf
    backrefs: yes
    regexp: "^({{ item }})"
    line: '\1 syslog'
    state: present
  with_items:
    - AccessLog
    - ErrorLog
    - PageLog

- name: Enable and start CUPS
  service:
    name: org.cups.cupsd.service
    enabled: yes
    state: started
