- name: Install bluetooth libraries and tools
  pacman:
    name:
      - bluez
      - bluez-utils
      # Pick one of following three GUI clients
      - blueman
      # - bluedevil  # KDE
      # - blueberry  # Mint
    state: present
  become: yes

# Don't remember why this was needed
# - name: Setup Bluetooth permissions
#   become: yes
#   copy:
#     src: 40-bluetooth.rules
#     dest: /etc/polkit-1/rules.d/40-bluetooth.rules
#     mode: 0644

- name: Create lp group
  group:
    name: lp
    state: present

# Needed to connect to a Bluetooth tether
- name: Add user to lp group
  user:
    name: "{{ user.name }}"
    groups: lp
    append: yes

- name: Enable and start the bluetooth service
  service:
    name: bluetooth.service
    enabled: yes
    state: started

# Should be default now as of BlueZ 5.65
# - name: Start bluetooth automatically, for LightDM
#   lineinfile:
#     path: /etc/bluetooth/main.conf
#     regexp: "^#? ?AutoEnable *="
#     state: present
#     line: "AutoEnable=true"
