- name: Install bluetooth libraries and tools
  aur:
    name:
      - libldac
      # As of 2020-09-14, needed to use testing/pulseaudio-bluetooth and testing/pulseaudio
      - "testing/pulseaudio-bluetooth"
      # - pulseaudio-modules-bt-git  # provides pulseaudio-bluetooth
      - blueman  # requires bluez, blues-libs
      - bluez-utils
  become: yes
  become_user: aur_builder
  notify:
    - restart pulse as user

- name: Auto-switch between HSP/HSF and A2DP
  lineinfile:
      dest: /etc/pulse/default.pa
      regex: "^load-module module-bluetooth-policy"
      state: present
      line: "load-module module-bluetooth-policy auto_switch=2"
  notify:
  - restart pulse as user

- name: Stop switching audio to HDMI every time display wakes up, etc.
  # https://askubuntu.com/a/228623/354276
  lineinfile:
    dest: /etc/pulse/default.pa
    regex: "^load-module module-switch-on-port-available"
    state: present
    line: "# load-module module-switch-on-port-available"
  notify:
  - restart pulse as user

- name: Try to prevent 1s silence at start audio to BT
  # https://askubuntu.com/a/440787
  lineinfile:
    dest: /etc/pulse/default.pa
    regex: "^load-module module-suspend-on-idle"
    state: present
    line: "# load-module module-suspend-on-idle"
  notify:
  - restart pulse as user

- name: Setup Bluetooth permissions
  become: yes
  copy:
    src: 40-bluetooth.rules
    dest: /etc/polkit-1/rules.d/40-bluetooth.rules
    mode: 0644

- name: Create lp group
  group:
    name: lp
    state: present

- name: Add user to lp group
  user:
    name: "{{ user.name }}"
    groups: lp
    append: yes

- name: Unblock the bluetooth service
  service:
    name: "rfkill-block@bluetooth.service"
    enabled: no
    state: stopped
  when: not bluetooth.disable

- name: Enable and start the bluetooth service
  service:
    name: bluetooth.service
    enabled: yes
    state: started
  when: not bluetooth.disable

- name: Disable and stop the bluetooth service
  service:
    name: bluetooth.service
    enabled: no
    state: stopped
  when: bluetooth.disable

- name: Block the bluetooth service
  service:
    name: "rfkill-block@bluetooth.service"
    enabled: yes
    state: started
  when: bluetooth.disable

- name: Start bluetooth automatically, for LightDM
  lineinfile:
    path: /etc/bluetooth/main.conf
    regexp: "^#? ?AutoEnable *="
    state: present
    line: "AutoEnable=true"
  when: not bluetooth.disable

