- name: Install bluetooth libraries and tools
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
      - pulseaudio-bluetooth
      - bluez
      - bluez-libs
      - bluez-utils
      - bluez-firmware
      - blueman
  notify:
    - restart pulse as user

- name: Setup Bluetooth permissions
  become: yes
  copy:
    src: 40-bluetooth.rules
    dest: /etc/polkit-1/rules.d/40-bluetooth.rules
    mode: 0644

- name: Unblock the bluetooth service
  service:
    name: "rfkill-block@bluetooth.service"
    enabled: no
    state: stopped
  when: bluetooth.disable == False

- name: Enable and start the bluetooth service
  service:
    name: bluetooth.service
    enabled: yes
    state: started
  when: bluetooth.disable == False

- name: Disable and stop the bluetooth service
  service:
    name: bluetooth.service
    enabled: no
    state: stopped
  when: bluetooth.disable == True

- name: Block the bluetooth service
  service:
    name: "rfkill-block@bluetooth.service"
    enabled: yes
    state: started
  when: bluetooth.disable == True

- name: Start bluetooth automatically, for LightDM
  lineinfile:
    path: /etc/bluetooth/main.conf
    regexp: "^#? ?AutoEnable *="
    state: present
    line: "AutoEnable=true"

