---
- name: Install i3
  pacman: name={{ item }} state=present
  with_items:
      - i3-wm
      - i3blocks
      - i3lock
      - i3status

- name: Install py3status
  aur: name=py3status user={{ user.name }}
  tags:
    - aur

- name: Verify that default applications file exists
  file: path=/etc/xdg/mimeapps.list state=touch

- name: Verify header in default applications file
  lineinfile: dest=/etc/xdg/mimeapps.list
              state=present
              line='[Default Applications]'
              insertbefore=BOF

- include: rofi.yml
