---
- name: Install i3 tiling window manager
  aur:
    name: "{{ item }}"
  become: yes
  become_user: aur_builder
  with_flattened:
    - i3-gaps
    - i3blocks
    - rofi
    - playerctl
    - qt5ct # https://wiki.archlinux.org/index.php/Qt#Configuration_of_Qt5_apps_under_environments_other_than_KDE_Plasma
    - compton-tryone-git # better blur than compton
    - xbindkeys
    - [ escrotum-git, python2-numpy ]
    - breeze-gtk # need to check if this gets what i want

# - name: Verify default applications file exists
#   file:
#     path: /etc/xdg/mimeapps.list
#     state: touch

# https://github.com/ansible/ansible/issues/38219
# - name: Verify header in default applications file
#   lineinfile:
#     dest: /etc/xdg/mimeapps.list
#     state: present
#     line: '[Default Applications]'
#     insertbefore: BOF
#     create: yes

- name: Install i3blocks-contrib scripts
  git:
    repo: "git://github.com/vivien/i3blocks-contrib.git"
    dest: "/home/{{ user.name }}/.config/i3blocks-contrib"
    update: yes
    accept_hostkey: yes
  become: yes
  become_user: "{{ user.name }}"

# https://github.com/vivien/i3blocks-contrib/tree/master/usb
- name: Configure USB reload script for i3blocks
  copy:
    src: 70-persistent-usb.rules
    dest: /etc/udev/rules.d/70-persistent-usb.rules
- name: udevadm control --reload-rules
  command: "udevadm control --reload-rules"
  become: yes

- name: Create kbdrate service
  copy:
    src: kbdrate.service
    dest: /etc/systemd/system/kbdrate.service

- name: Enable and start kbdrate service
  service:
    name: kbdrate.service
    enabled: yes
    state: started

# needs abstraction
- name: Install screen toggling script
  template:
    src: monitor
    dest: "/usr/local/bin/monitor"
    mode: 0755
  when: "'ThinkPad' in ansible_product_version"

- name: Install screen toggling script 2
  copy:
    src: monitor2
    dest: "/usr/local/bin/monitor2"
    mode: 0755
  when: "'ThinkPad' in ansible_product_version"
