---
- name: Install i3 tiling window manager
  aur:
    name: "{{ item }}"
  become: yes
  become_user: aur_builder
  with_items:
    - i3-gaps-next-git
    - i3blocks-git
    - rofi

- name: Verify default applications file exists
  file:
    path: /etc/xdg/mimeapps.list
    state: touch

- name: Verify header in default applications file
  lineinfile:
    dest: /etc/xdg/mimeapps.list
    state: present
    line: '[Default Applications]'
    insertbefore: BOF

