---

- name: Install RedShift
  when: "'redshift' in roles"
  block:
  - name: Install RedShift and dependencies
    pacman:
      state: present
      name:
        - librsvg
        - python-gobject
        - python-xdg
        - redshift
  - name: Setup redshift firejail
    when: "'firejail' in roles"
    block:
    - name: Jail RedShift
      file:
        src: /usr/bin/firejail
        dest: /usr/local/bin/redshift
        state: link
    - name: Jail RedShift GTK
      file:
        src: /usr/bin/firejail
        dest: /usr/local/bin/redshift-gtk
        state: link
    - name: Push RedShift firejail profile
      copy:
        src: firejail/redshift.profile
        dest: /usr/local/etc/firejail/redshift.profile
      notify:
        - activate firejail profiles
    - name: Push RedShift GTK firejail profile
      copy:
        src: firejail/redshift.profile
        dest: /usr/local/etc/firejail/redshift-gtk.profile
      notify:
        - activate firejail profiles
  - name: Allow RedShift to access geoclue
    blockinfile:
      dest: /etc/geoclue/geoclue.conf
      block: |
        [redshift]
        allowed=true
        system=false
        users=

- name: Remove RedShift
  when: "'redshift' not in roles"
  block:
  - name: Remove RedShift and dependencies
    pacman:
      state: absent
      name:
        - librsvg
        - python-gobject
        - python-xdg
        - redshift
  - name: Allow RedShift to access geoclue
    blockinfile:
      dest: /etc/geoclue/geoclue.conf
      block: |
        [redshift]
        allowed=true
        system=false
        users=
      state: absent

- name: Remove redshift firejail
  when: "'firejail' not in roles"
  block:
  - name: Unjail RedShift
    file:
      path: /usr/local/bin/redshift
      state: absent
  - name: Unjail RedShift GTK
    file:
      path: /usr/local/bin/redshift-gtk
      state: absent
  - name: Remove RedShift firejail profile
    file:
      path: /usr/local/etc/firejail/redshift.profile
      state: absent
  - name: Remove RedShift GTK firejail profile
    file:
      path: /usr/local/etc/firejail/redshift-gtk.profile
      state: absent

