---
- name: Install RedShift and dependencies
  pacman: name={{ item }} state=present
  with_items:
    - librsvg
    - python-gobject
    - python-xdg
    - redshift

- name: Jail RedShift
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/redshift
        state=link

- name: Jail RedShift GTK
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/redshift-gtk
        state=link

- name: Push RedShift firejail profile
  copy: src=firejail/redshift.profile dest=/usr/local/etc/firejail/redshift.profile
  notify:
    - activate firejail profiles

- name: Push RedShift GTK firejail profile
  copy: src=firejail/redshift.profile dest=/usr/local/etc/firejail/redshift-gtk.profile
  notify:
    - activate firejail profiles

- name: Allow RedShift to access geoclue
  blockinfile:
    dest: /etc/geoclue/geoclue.conf
    block: |
      [redshift]
      allowed=true
      system=false
      users=
