#!/bin/sh

# https://github.com/mathiasbynens/dotfiles/blob/master/.functions

# `a` with no arguments opens the current directory in Atom Editor, otherwise
# opens the given location

if [ $# -eq 0 ]; then
  atom .;
else
  atom "$@";
fi;
