#!/bin/sh

# https://github.com/mathiasbynens/dotfiles/blob/master/.functions

# `o` with no arguments opens the current directory, otherwise opens the given
# location

if [ $# -eq 0 ]; then
	open .;
else
	open "$@";
fi;
