#!/bin/sh

# https://github.com/mathiasbynens/dotfiles/blob/master/.functions

# `v` with no arguments opens the current directory in Vim, otherwise opens the
# given location

if [ $# -eq 0 ]; then
	vim .;
else
	vim "$@";
fi;
