---
- name: Install LightDM
  pacman: name={{ item }} state=present
  with_items:
      - lightdm
      - lightdm-webkit2-greeter

- name: Enable LightDM
  service:
    name: lightdm.service
    enabled: yes

- name: Create background dir
  file:
    path: /usr/share/backgrounds
    state: directory

- name: Push LightDM greeter background
  copy:
    src: taipei.jpg
    dest: /usr/share/backgrounds/taipei.jpg

- name: Specify LightDM greeter background
  lineinfile:
    dest: /etc/lightdm/lightdm-webkit2-greeter.conf
    regexp: "^background="
    state: present
    line: "background=/usr/share/backgrounds/taipei.jpg"

- name: Hide user images
  lineinfile:
    dest: /etc/lightdm/lightdm-webkit2-greeter.conf
    regexp: "^hide-user-image="
    state: present
    line: "hide-user-image=true"

- name: Force LightDM greeter theme
  lineinfile:
    dest: /usr/share/xgreeters/lightdm-webkit2-greeter.desktop
    regexp: "^Exec="
    state: present
    line: "Exec=env GTK_THEME=Adwaita:dark lightdm-webkit2-greeter"
