---
- name: Install LightDM
  aur:
    name: "{{ item }}"
  become: yes
  become_user: aur_builder
  with_items:
      - lightdm
      - lightdm-webkit2-greeter
      - lightdm-webkit2-theme-material2
      - accountsservice

- name: Enable LightDM
  service:
    name: lightdm.service
    enabled: yes

- name: Create background dir
  file:
    path: /usr/share/backgrounds
    state: directory

- name: Push LightDM greeter background
  copy:
    src: taipei.jpg
    dest: /usr/share/backgrounds/taipei.jpg
    mode: 0666

- name: Create user avatars dir
  file:
    path: /var/lib/AccountsService/users
    state: directory

- name: Push user avatar
  copy:
    src: cgorichanaz.png
    dest: /var/lib/AccountsService/users/cgorichanaz
    mode: 0666

- name: Create LightDM settings directory
  file:
    name: /etc/lightdm/lightdm.conf.d
    state: directory
    mode: 0755

- name: Specify LightDM settings
  copy:
    src: 50-lightdm.conf
    dest: /etc/lightdm/lightdm.conf.d/50-lightdm.conf
    mode: 0644

- name: Create LightDM greeter settings directory
  file:
    name: /etc/lightdm/lightdm-webkit2-greeter.conf.d
    state: directory
    mode: 0755

- name: Specify LightDM greeter settings
  copy:
    src: 50-lightdm-greeter.conf
    dest: /etc/lightdm/lightdm-webkit2-greeter.conf.d/50-lightdm-greeter.conf
    mode: 0644

- name: Specify LightDM greeter keyboard settings
  copy:
    src: 50-modify-indicators.conf
    dest: /etc/lightdm/lightdm-webkit2-greeter.conf.d/50-modify-indicators.conf
    mode: 0644

- name: Hide AUR user
  # could also make aur_builder have ID<1000
  lineinfile:
    path: /etc/lightdm/users.conf
    regexp: "^#? ?hidden-users *="
    state: present
    line: "hidden-users=nobody nobody4 noaccess aur_builder"

# for lightdm-gtk-greeter only
# - name: Hide user images
#   lineinfile:
#     dest: /etc/lightdm/lightdm-webkit2-greeter.conf
#     regexp: "^#? ?hide-user-image *="
#     state: present
#     line: "hide-user-image   = true"

- name: Force LightDM greeter theme
  lineinfile:
    dest: /usr/share/xgreeters/lightdm-webkit2-greeter.desktop
    regexp: "^Exec="
    state: present
    line: "Exec=env GTK_THEME=Adwaita:dark lightdm-webkit2-greeter"
