---
- name: Install Pipewire
  pacman:
    state: present
    name:
      - pipewire
      # - pipewire-alsa   # provides ALSA compat, not sure if need yet
      - pipewire-pulse  # provides Pulse compat
      - pavucontrol
