---
# - name: Install alsa-utils
#   pacman:
#     name: alsa-utils
#     state: present

- name: Install PulseAudio
  apt:
    state: present
    name:
      - pulseaudio
      # - pulseaudio-alsa  # Not sure if needed on Debian
      - pavucontrol

# might already be the case
# - name: Switch output to newly connected devices
#   lineinfile:
#     dest: /etc/pulse/default.pa
#     state: present
#     line: "load-module module-switch-on-connect"

# Not sure what this was for
# - name: Install pulseaudio-ctl
#   aur:
#     name: pulseaudio-ctl
#   become: yes
#   become_user: aur_builder
