---
- name: Install firejail
  pacman: name=firejail state=present

- name: Install firejail profile update script
  copy: src=profile-activate.sh dest=/usr/local/bin/profile-activate mode=0755

- name: Install firewarden.sh script
  copy: src=firewarden/firewarden dest=/usr/local/bin/firewarden mode=0755

- name: Create firejail profile directory
  file: path=/usr/local/etc/firejail state=directory

- name: Push firejail blacklist include
  template: src=disable-more.inc.j2 dest=/usr/local/etc/firejail/disable-more.inc

- name: Push generic firejail profile
  copy: src=generic.profile dest=/usr/local/etc/firejail/generic.profile
  notify:
    - activate firejail profiles
