---
# Enable [nested virtualization][nested]. Set the `nested_virt` fact
# to `true` if we have Intel processors and the `vmx` flag or we have
# AMD processors and the `svm` flag.
#
# [nested]: https://www.kernel.org/doc/Documentation/virtual/kvm/nested-vmx.txt
- name: set nested_virt fact
  set_fact:
    nested_virt: >-
      {{ ((is_intel and 'vmx' in cpu_flags)
      or (is_amd and 'svm' in cpu_flags))|bool }}

# Configure appropriate options for the vendor-specific kvm module
# in `/etc/modprobe.d/kvm.conf`.  This will result in either:
#
#     options kvm_intel nested=1
#
# Or:
#
#     options kvm_adm nested=1
#
# (Depending on the processor vendor)
- name: configure kvm module
  copy:
    dest: /etc/modprobe.d/kvm.conf
    content: |
      options kvm_intel nested=1 {{kvm_intel_options}}
      options kvm_amd nested=1 {{kvm_amd_options}}
  when: "{{ nested_virt }}"
  become: true

# Immediately load the appropriate kvm vendor module.
- name: load kvm module [intel]
  command: modprobe kvm_intel
  when: is_intel is success
  become: true

- name: load kvm module [amd]
  command: modprobe kvm_amd
  when: is_amd is success
  become: true

# List the appropriate kvm vendor module in
# `/etc/modules-load.d/ooo_kvm.conf`.  This will cause the module
# to be loaded automatically next time the system boots.
- name: arrange for kvm module to load at boot [intel]
  copy:
    content: kvm_intel
    dest: /etc/modules-load.d/ooo_kvm.conf
  when: is_intel is success
  become: true

- name: arrange for kvm module to load at boot [amd]
  copy:
    content: kvm_amd
    dest: /etc/modules-load.d/ooo_kvm.conf
  when: is_amd is success
  become: true
