# ~/.xprofile runs first, before xmodmap
# ~/.xsession runs last in /etc/lightdm/Xsession
# errors logged to ~/.xsession-errors
set -x

logger () {
  echo "$@" | systemd-cat -t $(basename $0)
}

export QT_QPA_PLATFORMTHEME=qt5ct
# didn't test next two yet
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCALE_FACTOR=1

# This definitely gets reset sometimes, possibly after connecting monitor/dock
# or after suspend, but likely the former as I don't suspend often. It seemed to
# be getting reset to the value in ansible/roles/lightdm/files/50-lightdm.conf
xset r rate 444 44

#xset -dpms

libinput-gestures-setup start &

if ! pgrep imwheel; then
  imwheel --buttons "45" &
fi

# this was broken before, but not sure if i needed it or implemented differently
# on_device_change &
# OK commenting out might be getting triggered too much ~/bin/on_device_change &
# $PATH is not fully set up here
# printf "\$PATH is $PATH" 1>&2

if pgrep xbindkeys; then pkill -9 xbindkeys; fi
xbindkeys &

if pgrep xmodmap; then pkill -9 xmodmap; fi
xmodmap ~/.Xmodmap

#!!!!disabling spacebar modifier to compare
# spacebar as modifier; depends on commands in ~/.Xmodmap
#logger "xcape: $(pgrep xcape | tr '\n' ' ')"
#if pgrep xcape; then pkill -9 xcape; fi
#xcape -e "Super_R=space"
#logger "xcape: $(pgrep xcape | tr '\n' ' ')"

~/bin/autolock &

# custom script to handle lid open/close, maybe more
if ! pgrep acpi_socket; then
  ~/bin/acpi_socket &
fi
