# ~/.xprofile runs first, before xmodmap
# ~/.xsession runs last in /etc/lightdm/Xsession

export QT_QPA_PLATFORMTHEME=qt5ct

xset r rate 350    50
xset -dpms

if pgrep xbindkeys; then pkill xbindkeys; fi
xbindkeys

if pgrep xmodmap; then pkill xmodmap; fi
xmodmap ~/.Xmodmap

# spacebar as modifier; depends on commands in ~/.Xmodmap
if pgrep xcape; then pkill xcape; fi
xcape -e "Super_R=space"

~/bin/autolock

# custom script to handle lid open/close, maybe more
if pgrep acpi_socket; then pkill acpi_socket; fi
~/bin/acpi_socket &
