---
- name: Install beets and dependencies
  pacman: name={{ item }} state=present
  with_items:
    - python2-pylast
    - python2-requests
    - python2-pyacoustid
    - python2-beautifulsoup4
    - gstreamer0.10-bad-plugins
    - gstreamer0.10-good-plugins
    - gstreamer0.10-ffmpeg
    - gstreamer0.10-python
    - gstreamer0.10-ugly
    - beets
  tags:
    - beets
