---
- name: Install poppler-glib
  pacman: name=poppler-glib state=present
  tags:
    - gimp

- name: Install GIMP
  pacman: name=gimp state=present
  tags:
    - gimp

- name: Install GIMP raw support
  pacman: name=gimp-ufraw state=present
  tags:
    - gimp
