---
- name: Install teiler and dependencies
  aur: name=ledger user={{ user.name }}
  aur: name={{ item }} user={{ user.name }}
  with_items:
    - xininfo-git
    - copyq-git
    - teiler-git
  tags:
    - aur
    - teiler
