---
- name: Install acpi_call for TLP battery functions
  pacman: name=acpi_call state=present
  tags:
    - battery

- name: Install tpacpi-bat
  aur: name=tpacpi-bat user={{ user.name }}
  tags:
    - aur
    - battery
