---
- name: Install tpfanco
  aur: name=tpfanco-svn user={{ user.name }}
  tags:
    - aur
    - fan

- name: Copy tpfanco configuration file
  copy: src=thinkfan.conf dest=/etc/thinkfan.conf
  tags:
    - aur
    - fan

- name: Enable and start tpfanco
  service: name=tpfand enabled=yes state=started
  tags:
    - aur
    - fan
