---
- hosts: all
  # ignore_errors: yes  # TODO
  roles:
    - { role: base, tags: ['base'] }
    - { role: x, tags: ['x'] }
    - {
      role: desktop_environment,
      tags: ['desktop_environment'],
      when: "desktop_environment is defined"
      }
    # - { role: laptop, tags: ['laptop'] }
    - { role: google, tags: ['google'] }
    - { role: i3, tags: ['i3'], when: desktop_environment == "i3" }
    # - { role: dell_xps, tags: ['dell_xps'], when: "'XPS' in ansible_product_name" }
    # - { role: thinkpad, tags: ['thinkpad'], when: "'ThinkPad' in ansible_product_version" }

    # - { role: archive, tags: ['archive'] }
    # - { role: android, tags: ['android'] }
    # - { role: arduino, tags: ['arduino'] }
    # - { role: bluetooth, tags: ['bluetooth'] }
    # - { role: browsers, tags: ['browsers'] }
    # - { role: cpu, tags: ['cpu'] }
    # - { role: cron, tags: ['cron'] }
    # - { role: cups, tags: ['cups'] }
    # - { role: docker, tags: ['docker'] }
    # - { role: dotfiles, tags: ['dotfiles'] }
    - { role: dvorak, tags: ['dvorak'], when: "'dvorak' in user.layout" }
    - { role: editors, tags: ['editors'] }
    # - { role: foldingathome, tags: ['foldingathome'], when: "'foldingathome' in flags" }
    # - { role: filesystems, tags: ['filesystems'] }
    # - { role: gnupg, tags: ['gnupg'] }
    # - { role: hostsctl, tags: ['hostsctl'], when: "hostsctl is defined" }
    # - { role: lightdm, tags: ['lightdm'] }  # login manager
    # - { role: localtime, tags: ['localtime'], when: "localtime is defined" }
    # - { role: media, tags: ['media'] }
    # - { role: nettools, tags: ['nettools'] }
    # - { role: networkmanager, tags: ['networkmanager'] }
    # - { role: ntp, tags: ['ntp'] }
    # - { role: office, tags: ['office'] }
    # # refreshes individual keys in your GnuPG keyring
    # - { role: parcimonie, tags: ['parcimonie'], when: "tor is defined" }
    # - { role: screensaver, tags: ['screensaver'] }
    - { role: sound, tags: ['sound'] }
    # - { role: spell, tags: ['spell'] }
    # - { role: ssd, tags: ['ssd'] }
    # - { role: ssh, tags: ['ssh'] }
    # - { role: udisks, tags: ['udisks'] }
    # - { role: virtualbox, tags: ['virtualbox'] }
    # - { role: virtualenv, tags: ['virtualenv'] }

    # - { role: taskwarrior, tags: ['taskwarrior'] }  # manages your to do list from the command line
