---
- hosts: all
  become: yes
  # ignore_errors: yes  # TODO
  roles:
    - { role: base, tags: ['base'] }
    - { role: desktop_environment, tags: ['desktop_environment'], when: "desktop_environment is defined" }
    - { role: archive, tags: ['archive'] }
    - { role: arduino, tags: ['arduino'] }
    - { role: bluetooth, tags: ['bluetooth'] }
    - { role: cpu, tags: ['cpu'] }
    - { role: cron, tags: ['cron'] }
    - { role: cups, tags: ['cups'] }
    - { role: docker, tags: ['docker'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: editors, tags: ['editors'] }
    - { role: filesystems, tags: ['filesystems'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: hostsctl, tags: ['hostsctl'], when: "hostsctl is defined" }
    - { role: media, tags: ['media'] }
    - { role: networking, tags: ['networking'] }
    - { role: ntp, tags: ['ntp'] }
    - { role: office, tags: ['office'] }
    - { role: server, tags: ['server'], when: "'server' in flags" }
    - { role: sound, tags: ['sound'] }
    - { role: ssd, tags: ['ssd'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: sway, tags: ['sway'], when: desktop_environment == "sway" }
    - { role: greeter, tags: ['greeter'], when: desktop_environment == "sway" }
    - { role: udisks, tags: ['udisks'] }
    - { role: virtualbox, tags: ['virtualbox'] }
    # - { role: dell_xps, tags: ['dell_xps'], when: "'XPS' in ansible_product_name" }
    - { role: omen, tags: ['omen'], when: "'OMEN Transcend Gaming Laptop 14t-fb000' in ansible_product_name" }

  vars:
    # TODO
    - { role: gnupg, tags: ['gnupg'] }
    - { role: virtualenv, tags: ['virtualenv'] }
    # TO CONSIDER
    - { role: bertvv.samba, tags: ['samba'] }
    - { role: iptables, tags: ['iptables'] }
    - { role: localtime, tags: ['localtime'], when: "localtime is defined" }
    - { role: screensaver, tags: ['screensaver'] }
    - { role: tor, tags: ['tor'] }
    - { role: unbound, tags: ['unbound'] }  # validating, recursive, and caching DNS resolver
    # TO SAVE
    - { role: android, tags: ['android'] }
    - { role: foldingathome, tags: ['foldingathome'], when: "'foldingathome' in flags" }
    - { role: i3, tags: ['i3'], when: desktop_environment == "i3" }
    - { role: laptop, tags: ['laptop'], when: "'Precision' in ansible_product_name or 'XPS' in ansible_product_name" }

  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"
