---
- name: Download rcm
  command: cower -dq rcm
           chdir=/home/{{ user.name }}/{{ aur.dir }}
           creates=/home/{{ user.name }}/{{ aur.dir }}/rcm
  when: dotfiles is defined
  tags:
    - aur
    - dotfiles
  become: yes
  become_user: "{{ user.name }}"

- name: Build and install rcm
  command: "{{ aur.makepkg }} chdir=/home/{{ user.name }}/{{ aur.dir }}/rcm"
  when: dotfiles is defined
  tags:
    - aur
    - dotfiles
  become: yes
  become_user: "{{ user.name }}"

- name: Clone user dotfiles
  git: repo={{ dotfiles.url }} dest=/home/{{ user.name }}/.dotfiles accept_hostkey=yes update=no
  when: dotfiles is defined
  become: yes
  become_user: "{{ user.name }}"
  tags:
    - dotfiles

- name: Install user dotfiles
  command: rcup {{ dotfiles.rcup_flags }}
  when: dotfiles is defined
  become: yes
  become_user: "{{ user.name }}"
  tags:
    - dotfiles
