---
- name: Install universal base packages
  pacman: name={{ item }} state=present
  with_items: "{{ base_packages }}"
  tags:
    - packages

- name: Create AUR directory
  file: path=/home/{{ user.name }}/{{ aur.dir }}
        state=directory
        owner={{ user.name }}
        group={{ user.group }}
  tags:
    - aur
    - packages

- name: Install cower
  aur: name=cower user={{ user.name }} skip_pgp=yes
  tags:
    - aur
    - packages

- name: Install AUR base packages
  aur: name={{ item }} user={{ user.name }}
  with_items: "{{ aur.packages }}"
  tags:
    - aur
    - packages
