---
- name: Install Bash
  pacman: name={{ item }} state=present
  with_items:
    - bash
    - bash-completion

- name: Install ZSH
  pacman: name={{ item }} state=present
  with_items:
    - zsh
    - zsh-completions
