---
- name: Install sudo
  pacman: name=sudo state=present

- name: Add user to wheel group
  user: name={{ user.name }} groups=wheel append=yes

- name: Copy sudo configuration
  copy: src=sudoers dest=/etc/sudoers mode=440
