
#ZSH_THEME="powerlevel10k/powerlevel10k"

DEFAULT_USER=$USER

#POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir dir_writable rbenv vcs)
#POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs command_execution_time time)
# custom_comment
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(time command_execution_time context dir dir_writable root_indicator rbenv vcs background_jobs status) #newline custom_indicator
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_DISABLE_RPROMPT=true
POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=""
#POWERLEVEL9K_WHITESPACE_BETWEEN_LEFT_SEGMENTS=""
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=" "

#POWERLEVEL9K_CUSTOM_INDICATOR="if [[ $(whoami) = cgorichanaz ]]; then echo '$'; fi"
POWERLEVEL9K_CUSTOM_INDICATOR="echo '$'"
POWERLEVEL9K_CUSTOM_COMMENT="echo '#'"

POWERLEVEL9K_PROMPT_ON_NEWLINE=true # default false
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="# "
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="$ "

POWERLEVEL9K_DIR_HOME_FOREGROUND='000'
POWERLEVEL9K_DIR_HOME_BACKGROUND='012'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='016'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='012'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='057'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='007'
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND='015'
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND='001'


POWERLEVEL9K_STATUS_OK=false
POWERLEVEL9K_STATUS_HIDE_SIGNAME=true
POWERLEVEL9K_DIR_SHOW_WRITABLE=false # default false
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_to_unique"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=3
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='000'
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='003'
POWERLEVEL9K_STATUS_OK_BACKGROUND="000"
POWERLEVEL9K_STATUS_OK_FOREGROUND="015"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="001"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="015"
POWERLEVEL9K_TIME_FOREGROUND='015'
POWERLEVEL9K_TIME_BACKGROUND='009'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='000'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='039'
POWERLEVEL9K_EXECUTION_TIME_ICON=''

#POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind git-stash git-remotebranch git-tagname)
#POWERLEVEL9K_VCS_HIDE_TAGS=true
#POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY=false
#POWERLEVEL9K_SHOW_CHANGESET=false
#POWERLEVEL9K_HIDE_BRANCH_ICON=true


