---
- name: Install alsa-utils
  pacman: name=alsa-utils state=present

- name: Copy udev rule for USB audio device switching
  copy: src=udev.rules dest=/etc/udev/rules.d/00-local.rules

- name: Push volume control script
  copy: src=volume.sh dest=/usr/local/bin/volume mode=0755
