---
- name: Install xautolock
  pacman: name=xautolock state=present

- name: Install physlock
  aur: name=physlock user={{ user.name }}
  tags:
    - aur

- name: Push sleep lock script
  template: src=lock.sh.j2 dest=/usr/lib/systemd/system-sleep/lock.sh mode=755
