---
- name: Install xautolock
  pacman: name=xautolock state=present

- name: Install physlock
  aur: name=physlock user={{ user.name }}
  tags:
    - aur

- name: Push lock script
  copy: src=lock.sh dest=/usr/local/bin/lock mode=0755

- name: Push sleep lock script
  copy: src=sleeplock.sh dest=/usr/lib/systemd/system-sleep/lock.sh mode=0755
