---
- name: Install VirtualBox, dependencies, extensions
  aur:
    name: "{{ item }}"
  become: yes
  become_user: aur_builder
  with_items:
    - net-tools
    - virtualbox
    - virtualbox-guest-iso
    - virtualbox-host-dkms
    - virtualbox-ext-oracle

- name: Add the user to vboxusers group
  user:
    name: "{{ user.name }}"
    groups: vboxusers
    append: yes
