---
- name: Create vboxusers group
  group:
    name: vboxusers
    state: present

- name: Add user to vboxusers group
  user:
    name: "{{ user.name }}"
    groups: vboxusers
    append: yes

- name: Remove generic Virtualbox host modules
  pacman:
    name: virtualbox-host-dkms
    state: absent

- name: Install Virtualbox Arch host modules
  pacman:
    name:
      - virtualbox-host-modules-arch
    state: present

- name: Install VirtualBox, dependencies, extensions
  pacman:
    name:
      - net-tools
      - virtualbox
      - virtualbox-guest-iso
    state: present

- name: Install VirtualBox extensions
  aur:
    name: virtualbox-ext-oracle
  become: yes
  become_user: aur_builder
