---
- name: Install libOTR
  pacman: name=libotr state=present

- name: Install Bitlbee
  pacman: name=bitlbee state=present

- name: Push Bitlbee configuration file
  template: src=bitlbee.conf.j2 dest=/etc/bitlbee/bitlbee.conf

- name: Ensure proper ownership of configuration directory
  file: path=/var/lib/bitlbee group=bitlbee owner=bitlbee

- name: Create Bitlbee systemd unit file directory
  file: path=/etc/systemd/system/bitlbee.service.d state=directory
  tags:
    - firejail

- name: Push Bitlbee socket unit file
  copy: src=bitlbee-service-override.conf dest=/etc/systemd/system/bitlbee.service.d/override.conf
  notify:
    - reload systemd config
    - restart bitlbee
  tags:
    - firejail

- name: Enable and start Bitlbee
  service: name=bitlbee enabled=yes state=started
  when: bitlbee.run_on == "all"

- name: Remove Bitlbee from trusted unit list
  lineinfile: dest=/usr/local/etc/trusted_units
              state=absent
              line=bitlbee.service
  when: bitlbee.run_on == "all"

- name: Disable Bitlbee
  service: name=bitlbee enabled=no
  when: bitlbee.run_on == "trusted"

- name: Add Bitlbee to trusted unit list
  lineinfile: dest=/usr/local/etc/trusted_units
              state=present
              line=bitlbee.service
  when: bitlbee.run_on == "trusted"
