---
- name: Install hostsctl
  aur:
    name: hostsctl
  become: yes
  become_user: aur_builder

- name: Push hostsctl config
  template:
    src: hostsctl.conf.j2
    dest: /etc/hostsctl.conf

- name: Update hostsctl
  command: hostsctl update
  changed_when: False

- name: Unblock Google Analytics
  command: hostsctl enable google-analytics.com www.google-analytics.com ssl.google-analytics.com
  changed_when: False
  become: yes
