---
- name: Install hostsctl
  aur:
    name: hostsctl
  become: yes
  become_user: aur_builder

- name: Push hostsctl config
  template:
    src: hostsctl.conf.j2
    dest: /etc/hostsctl.conf

- name: Update hostsctl
  command: hostsctl update
