---
- name: Install beets and dependencies
  pacman: name={{ item }} state=present
  with_items:
    - gst-libav
    - gst-plugins-bad
    - gst-plugins-good
    - gst-plugins-ugly
    - gst-python
    - python-beautifulsoup4
    - python-gobject
    - python-pylast
    - python-requests
    - python-pyacoustid
    - beets
  tags:
    - beets

- name: Install mp3val
  aur: name=mp3val user={{ user.name }}
  tags:
    - aur
    - beets
