---
- name: Install poppler-glib
  pacman: name=poppler-glib state=present

- name: Install GIMP
  pacman: name={{ item }} state=present
  with_items:
    - gimp
    - gimp-plugin-gmic

- name: Jail GIMP
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/gimp
        state=link

- name: Install GIMP raw support
  pacman: name=gimp-nufraw state=present
