---
- name: Install poppler-glib
  pacman:
    name: poppler-glib
    state: present

- name: Install GIMP
  pacman:
    name:
      - gimp
      - gimp-plugin-gmic
      - xsane-gimp
    state: present

- name: Jail GIMP
  when: "'firejail' in roles"
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/gimp
    state: link

- name: Unjail GIMP
  when: "'firejail' not in roles"
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/gimp
    state: link

- name: Install GIMP raw support
  pacman:
    name: gimp-nufraw
    state: present

