---
- name: Install media tools
  aur:
    name: "{{ item }}"
  become: yes
  become_user: aur_builder
  with_flattened: "{{ packages.media }}"

- name: Jail feh
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/feh
        state=link

- name: Install Metadata Anonymisation Toolkit and dependencies
  aur: name={{ item }}
  become: yes
  become_user: aur_builder
  with_items:
    - hachoir-core
    - hachoir-parser
    - mat

# - import_tasks: beets.yml # the music geek's media organizer
- import_tasks: gimp.yml
- import_tasks: qcode.yml
